package svgen

import (
	"bytes"
	"fmt"
	"text/template"
	"time"
)

// LatencyConfig holds TLP response timing parameters for anti-fingerprinting.
// Values should ideally come from donor device profiling.
type LatencyConfig struct {
	MinCycles        int // minimum read response latency in clock cycles
	MaxCycles        int // maximum
	AvgCycles        int // average (used when jitter disabled)
	BurstCorrelation int // 0-255, higher = more correlated sequential timing
	ThermalPeriod    int // cycles between thermal drift baseline adjustments
}

// DefaultLatencyConfig returns device-class-appropriate latency defaults.
func DefaultLatencyConfig(classCode uint32) *LatencyConfig {
	baseClass := (classCode >> 16) & 0xFF
	subClass := (classCode >> 8) & 0xFF
	progIF := classCode & 0xFF

	switch {
	case baseClass == 0x01 && subClass == 0x08 && progIF == 0x02:
		// NVMe — SSDs are fast
		return &LatencyConfig{MinCycles: 3, MaxCycles: 12, AvgCycles: 6, BurstCorrelation: 160, ThermalPeriod: 49152}
	case baseClass == 0x0C && subClass == 0x03 && progIF == 0x30:
		// xHCI — USB controllers are moderate
		return &LatencyConfig{MinCycles: 4, MaxCycles: 18, AvgCycles: 8, BurstCorrelation: 140, ThermalPeriod: 40960}
	case baseClass == 0x02:
		// Ethernet — network controllers are fast
		return &LatencyConfig{MinCycles: 2, MaxCycles: 8, AvgCycles: 4, BurstCorrelation: 180, ThermalPeriod: 57344}
	default:
		return &LatencyConfig{MinCycles: 3, MaxCycles: 15, AvgCycles: 7, BurstCorrelation: 128, ThermalPeriod: 32768}
	}
}

// GenerateLatencyEmulatorSV renders tlp_latency_emulator.sv.
// This module delays TLP responses with realistic jitter.
func GenerateLatencyEmulatorSV(cfg *SVGeneratorConfig) (string, error) {
	tmpl, err := template.New("latency_emulator").Funcs(svFuncMap()).Parse(latencyEmulatorTmpl)
	if err != nil {
		return "", fmt.Errorf("parsing latency_emulator template: %w", err)
	}

	var buf bytes.Buffer
	if err := tmpl.Execute(&buf, cfg); err != nil {
		return "", fmt.Errorf("executing latency_emulator template: %w", err)
	}
	return buf.String(), nil
}

// BuildPRNGSeeds generates 4 deterministic but unique PRNG seeds from device IDs + entropy.
func BuildPRNGSeeds(vid, did uint16, entropy uint32) [4]uint32 {
	v := uint32(vid)
	d := uint32(did)
	return [4]uint32{
		(v ^ d) ^ entropy,
		((v << 16) | d) ^ ((entropy * 31) & 0xFFFFFFFF),
		(d ^ uint32(vid)) ^ ((entropy * 127) & 0xFFFFFFFF),
		v ^ ((entropy * 8191) & 0xFFFFFFFF),
	}
}

// BuildEntropyFromTime generates a build entropy seed from current time.
func BuildEntropyFromTime() uint32 {
	return uint32(time.Now().UnixNano() & 0xFFFFFFFF)
}

var latencyEmulatorTmpl = `//
// TLP Latency Emulator
//
// Auto-generated by PCILeechGen
// Device: {{ hex04 .DeviceIDs.VendorID }}:{{ hex04 .DeviceIDs.DeviceID }}
//
// Injects realistic response latency based on device class timing.
// Anti-fingerprinting: xorshift128+ PRNG, thermal drift, burst correlation,
// address-region variation. Each build produces unique timing patterns.
//

` + "`" + `timescale 1ns / 1ps

module tlp_latency_emulator #(
    parameter MIN_LATENCY_CYCLES = {{ .LatencyConfig.MinCycles }},
    parameter MAX_LATENCY_CYCLES = {{ .LatencyConfig.MaxCycles }},
    parameter AVG_LATENCY_CYCLES = {{ .LatencyConfig.AvgCycles }},
    parameter ENABLE_JITTER      = 1,
    parameter BURST_CORRELATION  = {{ .LatencyConfig.BurstCorrelation }},
    parameter THERMAL_DRIFT_PERIOD = {{ .LatencyConfig.ThermalPeriod }},
    // PRNG seeds — unique per build, derived from device IDs + build entropy
    parameter [31:0] PRNG_SEED_0 = 32'h{{ hex08 (index .PRNGSeeds 0) }},
    parameter [31:0] PRNG_SEED_1 = 32'h{{ hex08 (index .PRNGSeeds 1) }},
    parameter [31:0] PRNG_SEED_2 = 32'h{{ hex08 (index .PRNGSeeds 2) }},
    parameter [31:0] PRNG_SEED_3 = 32'h{{ hex08 (index .PRNGSeeds 3) }}
)(
    input wire          clk,
    input wire          rst,

    input wire          req_valid,
    input wire [87:0]   req_ctx,
    input wire [31:0]   req_data,
    input wire [31:0]   req_addr,
    output reg          req_ready,

    output reg          rsp_valid,
    output reg [87:0]   rsp_ctx,
    output reg [31:0]   rsp_data,
    input wire          rsp_ready
);

    reg [7:0] latency_counter;
    reg [7:0] target_latency;
    reg request_pending;

    reg [87:0] stored_ctx;
    reg [31:0] stored_data;

    // burst correlation tracking
    reg [31:0] prev_addr;
    reg [7:0]  prev_latency;
    reg        prev_valid;

    // ========================================================================
    // xorshift128+ PRNG — 2^128 state space, passes BigCrush
    // ========================================================================
    reg [31:0] prng_s0, prng_s1, prng_s2, prng_s3;
    wire [31:0] prng_out;
    wire [31:0] prng_next_s0, prng_next_s3;

    assign prng_next_s0 = prng_s0 ^ (prng_s0 << 11);
    assign prng_next_s3 = prng_s3 ^ (prng_s3 >> 19) ^ prng_next_s0 ^ (prng_next_s0 >> 8);
    assign prng_out = prng_s3 + prng_s0;

    always @(posedge clk) begin
        if (rst) begin
            prng_s0 <= PRNG_SEED_0;
            prng_s1 <= PRNG_SEED_1;
            prng_s2 <= PRNG_SEED_2;
            prng_s3 <= PRNG_SEED_3;
        end else if (req_valid && req_ready) begin
            prng_s0 <= prng_s1;
            prng_s1 <= prng_s2;
            prng_s2 <= prng_s3;
            prng_s3 <= prng_next_s3;
        end
    end

    // ========================================================================
    // Thermal drift — gradual baseline shift simulating temperature changes
    // ========================================================================
    reg [15:0] thermal_counter;
    reg [3:0]  thermal_offset;

    always @(posedge clk) begin
        if (rst) begin
            thermal_counter <= 16'h0;
            thermal_offset  <= 4'h0;
        end else begin
            thermal_counter <= thermal_counter + 1'b1;
            if (thermal_counter == THERMAL_DRIFT_PERIOD[15:0]) begin
                thermal_counter <= 16'h0;
                if (prng_out[0])
                    thermal_offset <= (thermal_offset < 4'h7) ? thermal_offset + 1'b1 : thermal_offset;
                else
                    thermal_offset <= (thermal_offset > 4'h8) ? thermal_offset - 1'b1 : thermal_offset;
            end
        end
    end

    // ========================================================================
    // Address-region-based latency variation
    // ========================================================================
    wire [2:0] addr_region = req_addr[14:12];
    wire [7:0] region_adjust = (addr_region == 3'h0) ? 8'h00 :
                               (addr_region == 3'h1) ? 8'h02 :
                               (addr_region == 3'h2) ? 8'h04 :
                               (addr_region == 3'h3) ? 8'h01 :
                               8'h03;

    // ========================================================================
    // Burst correlation — sequential accesses have correlated timing
    // ========================================================================
    wire is_sequential = prev_valid && ((req_addr[31:8] == prev_addr[31:8]) ||
                                        (req_addr[31:8] == prev_addr[31:8] + 1'b1));
    wire [7:0] corr_weight = is_sequential ? BURST_CORRELATION[7:0] : 8'h00;
    wire [7:0] correlated_latency = ((prev_latency * corr_weight) +
                                     (prng_out[7:0] * (8'hFF - corr_weight))) >> 8;

    // ========================================================================
    // Final latency computation
    // ========================================================================
    wire [7:0] latency_range = MAX_LATENCY_CYCLES - MIN_LATENCY_CYCLES + 1;
    wire [7:0] base_jitter = is_sequential ? correlated_latency : (prng_out[7:0] % latency_range);
    wire [7:0] thermal_adj = base_jitter + $signed(thermal_offset);
    wire [7:0] region_adj  = thermal_adj + region_adjust;
    wire [7:0] jittered    = (MIN_LATENCY_CYCLES + region_adj > MAX_LATENCY_CYCLES) ? MAX_LATENCY_CYCLES :
                             (MIN_LATENCY_CYCLES + region_adj < MIN_LATENCY_CYCLES) ? MIN_LATENCY_CYCLES :
                             MIN_LATENCY_CYCLES + region_adj;
    wire [7:0] computed_latency = ENABLE_JITTER ? jittered : AVG_LATENCY_CYCLES;

    always @(*) begin
        req_ready = !request_pending;
    end

    // ========================================================================
    // Latency state machine
    // ========================================================================
    always @(posedge clk) begin
        if (rst) begin
            request_pending <= 1'b0;
            latency_counter <= 8'h0;
            target_latency  <= AVG_LATENCY_CYCLES;
            rsp_valid       <= 1'b0;
            stored_ctx      <= 88'h0;
            stored_data     <= 32'h0;
            prev_addr       <= 32'h0;
            prev_latency    <= AVG_LATENCY_CYCLES;
            prev_valid      <= 1'b0;
        end else begin
            if (rsp_valid && rsp_ready)
                rsp_valid <= 1'b0;

            if (request_pending) begin
                if (latency_counter < target_latency) begin
                    latency_counter <= latency_counter + 8'h1;
                end else if (!rsp_valid || rsp_ready) begin
                    rsp_valid       <= 1'b1;
                    rsp_ctx         <= stored_ctx;
                    rsp_data        <= stored_data;
                    request_pending <= 1'b0;
                    latency_counter <= 8'h0;
                    prev_latency    <= target_latency;
                    prev_valid      <= 1'b1;
                end
            end else if (req_valid && req_ready) begin
                request_pending <= 1'b1;
                stored_ctx      <= req_ctx;
                stored_data     <= req_data;
                prev_addr       <= req_addr;
                latency_counter <= 8'h0;
                target_latency  <= computed_latency;
            end
        end
    end

endmodule
`
