package svgen

// MSI-X table SV template.

var msixTableTmpl = `//
// MSI-X Table — {{ .MSIXConfig.NumVectors }} vectors
// Auto-generated by PCILeechGen
// Device: {{ hex04 .DeviceIDs.VendorID }}:{{ hex04 .DeviceIDs.DeviceID }}
//

` + "`timescale 1ns / 1ps`" + `

module pcileech_msix_table #(
    parameter NUM_VECTORS    = {{ .MSIXConfig.NumVectors }},
    parameter TABLE_OFFSET   = 32'h{{ printf "%08X" .MSIXConfig.TableOffset }},
    parameter PBA_OFFSET     = 32'h{{ printf "%08X" .MSIXConfig.PBAOffset }},
    parameter TABLE_ENTRIES  = NUM_VECTORS * 4  // DWORDs
)(
    input               rst,
    input               clk,

    // BAR write interface
    input [31:0]        wr_addr,
    input [31:0]        wr_data,
    input [3:0]         wr_be,
    input               wr_valid,

    // BAR read interface
    input [87:0]        rd_req_ctx,
    input [31:0]        rd_req_addr,
    input               rd_req_valid,

    output reg [87:0]   rd_rsp_ctx,
    output reg [31:0]   rd_rsp_data,
    output reg          rd_rsp_valid,

    output              addr_hit  // request targets MSI-X region
);

    // address decode
    localparam TABLE_END = TABLE_OFFSET + NUM_VECTORS * 16;
    localparam PBA_SIZE  = ((NUM_VECTORS + 63) / 64) * 8;
    localparam PBA_END   = PBA_OFFSET + PBA_SIZE;

    wire is_table = (rd_req_addr >= TABLE_OFFSET) && (rd_req_addr < TABLE_END);
    wire is_pba   = (rd_req_addr >= PBA_OFFSET) && (rd_req_addr < PBA_END);
    assign addr_hit = rd_req_valid && (is_table || is_pba);

    wire wr_is_table = (wr_addr >= TABLE_OFFSET) && (wr_addr < TABLE_END);

    // table BRAM
    (* ram_style = "block" *)
    reg [31:0] msix_table_ram [0:TABLE_ENTRIES-1];

    initial begin
        $readmemh("msix_table_init.hex", msix_table_ram);
    end

    // PBA — all cleared initially
    reg [31:0] msix_pba [0:((NUM_VECTORS+31)/32)-1];

    integer k;
    initial begin
        for (k = 0; k < (NUM_VECTORS+31)/32; k = k + 1)
            msix_pba[k] = 32'h0;
    end

    // write logic — table only (PBA is read-only)
    always @(posedge clk) begin
        if (!rst && wr_valid && wr_is_table) begin
            if (wr_be[0]) msix_table_ram[(wr_addr - TABLE_OFFSET) >> 2][7:0]   <= wr_data[7:0];
            if (wr_be[1]) msix_table_ram[(wr_addr - TABLE_OFFSET) >> 2][15:8]  <= wr_data[15:8];
            if (wr_be[2]) msix_table_ram[(wr_addr - TABLE_OFFSET) >> 2][23:16] <= wr_data[23:16];
            if (wr_be[3]) msix_table_ram[(wr_addr - TABLE_OFFSET) >> 2][31:24] <= wr_data[31:24];
        end
    end

    // read logic — 2-cycle pipeline
    reg [87:0] rd_ctx_d1;
    reg        rd_valid_d1;
    reg [31:0] rd_data_d1;

    always @(posedge clk) begin
        rd_ctx_d1   <= rd_req_ctx;
        rd_valid_d1 <= addr_hit;

        if (addr_hit) begin
            if (is_table)
                rd_data_d1 <= msix_table_ram[(rd_req_addr - TABLE_OFFSET) >> 2];
            else if (is_pba)
                rd_data_d1 <= msix_pba[(rd_req_addr - PBA_OFFSET) >> 2];
            else
                rd_data_d1 <= 32'h0;
        end else begin
            rd_data_d1 <= 32'h0;
        end
    end

    always @(posedge clk) begin
        rd_rsp_ctx   <= rd_ctx_d1;
        rd_rsp_valid <= rd_valid_d1;
        rd_rsp_data  <= rd_data_d1;
    end

endmodule
`

// MSIXConfig parameters for MSI-X SV template.
type MSIXConfig struct {
	NumVectors  int
	TableOffset uint32
	PBAOffset   uint32
}
