package svgen

// SV template strings. Kept separate from generator logic for readability.

var barImplDeviceTmpl = `//
// Device-Specific PCILeech BAR Implementation
//
// Auto-generated by PCILeechGen
// Device: {{ hex04 .DeviceIDs.VendorID }}:{{ hex04 .DeviceIDs.DeviceID }}
//
// Features:
//   - Register-accurate BAR read/write with byte-enable + RW mask
//   - 2-cycle read pipeline latency
{{ if .IsNVMe }}//   - NVMe CC.EN → CSTS.RDY state machine (dynamic handshake)
{{ end }}{{ if .HasMSIX }}//   - MSI-X interrupt controller (4-state FSM with LFSR jitter)
{{ end }}//

` + "`" + `timescale 1ns / 1ps
{{ if .BARModel }}
module pcileech_bar_impl_device #(
    parameter BAR_SIZE = {{ .BARModel.Size }}
)(
    input               rst,
    input               clk,

    input [31:0]        wr_addr,
    input [31:0]        wr_data,
    input [3:0]         wr_be,
    input               wr_valid,

    input [87:0]        rd_req_ctx,
    input [31:0]        rd_req_addr,
    input               rd_req_valid,

    output reg [87:0]   rd_rsp_ctx,
    output reg [31:0]   rd_rsp_data,
    output reg          rd_rsp_valid
);

    // ========================================================================
    // Register Storage
    // ========================================================================
{{ range .BARModel.Registers }}
    reg [{{ sub (mul .Width 8) 1 }}:0] reg_0x{{ hex08 .Offset }};  // {{ .Name }}
{{ end }}
{{ if .IsNVMe }}
    // ========================================================================
    // NVMe CC → CSTS State Machine
    // stornvme.sys polls CSTS.RDY after writing CC.EN — this is the #1 cause
    // of Code 10. Static CSTS values do NOT work; real transition is required.
    // ========================================================================
    reg        cc_en_prev;
    reg [3:0]  csts_transition_cnt;
    reg        csts_rdy_pending;

    always @(posedge clk) begin
        if (rst) begin
            cc_en_prev          <= 1'b1;
            csts_transition_cnt <= 4'h0;
            csts_rdy_pending    <= 1'b0;
        end else begin
            cc_en_prev <= reg_0x00000014[0]; // CC.EN

            // CC.EN rising edge → start RDY transition (2-8 cycle delay)
            if (reg_0x00000014[0] && !cc_en_prev) begin
                csts_rdy_pending    <= 1'b1;
                csts_transition_cnt <= 4'h0;
            end
            // CC.EN falling edge → immediate shutdown
            else if (!reg_0x00000014[0] && cc_en_prev) begin
                reg_0x0000001C[0]    <= 1'b0;        // CSTS.RDY = 0
                reg_0x0000001C[3:2]  <= 2'b10;       // CSTS.SHST = shutdown complete
                csts_rdy_pending     <= 1'b0;
            end

            // Pending RDY transition: count up then set RDY
            if (csts_rdy_pending) begin
                csts_transition_cnt <= csts_transition_cnt + 1'b1;
                if (csts_transition_cnt >= 4'h4) begin
                    reg_0x0000001C[0]   <= 1'b1;  // CSTS.RDY = 1
                    reg_0x0000001C[3:2] <= 2'b00;  // CSTS.SHST = no shutdown
                    csts_rdy_pending    <= 1'b0;
                end
            end
        end
    end
{{ end }}
{{ if .HasMSIX }}
    // ========================================================================
    // MSI-X Interrupt Controller — 4-state FSM
    //   IDLE → PENDING → ASSERT → COOLDOWN
    // Triggered when a writable register is modified.
    // LFSR-based jitter prevents timing fingerprinting.
    // ========================================================================
    localparam [1:0] INT_IDLE     = 2'b00;
    localparam [1:0] INT_PENDING  = 2'b01;
    localparam [1:0] INT_ASSERT   = 2'b10;
    localparam [1:0] INT_COOLDOWN = 2'b11;

    reg [1:0]  int_state;
    reg [5:0]  int_counter;
    reg [5:0]  int_cooldown_target;
    reg        int_trigger;

    // 16-bit LFSR for interrupt timing jitter
    reg [15:0] int_lfsr;
    wire int_lfsr_fb = int_lfsr[15] ^ int_lfsr[14] ^ int_lfsr[12] ^ int_lfsr[3];

    always @(posedge clk) begin
        if (rst)
            int_lfsr <= {4'h0, 4'h{{ hex02 .DeviceIDs.RevisionID }}, 8'h{{ hex02 (index (rwMaskBytes (index .PRNGSeeds 0)) 0) }}};
        else
            int_lfsr <= {int_lfsr[14:0], int_lfsr_fb};
    end

    // Write activity detection — any write to a writable register triggers
    always @(posedge clk) begin
        if (rst)
            int_trigger <= 1'b0;
        else
            int_trigger <= wr_valid;
    end

    always @(posedge clk) begin
        if (rst) begin
            int_state           <= INT_IDLE;
            int_counter         <= 6'h0;
            int_cooldown_target <= 6'h10;
        end else begin
            case (int_state)
                INT_IDLE: begin
                    if (int_trigger) begin
                        int_state   <= INT_PENDING;
                        int_counter <= 6'h0;
                    end
                end

                INT_PENDING: begin
                    int_counter <= int_counter + 1'b1;
                    // Random pending delay (2-6 cycles based on LFSR)
                    if (int_counter >= {4'h0, int_lfsr[1:0]} + 6'h2)
                        int_state <= INT_ASSERT;
                end

                INT_ASSERT: begin
                    // Assert for 1 cycle then cooldown
                    int_state <= INT_COOLDOWN;
                    int_counter <= 6'h0;
                    // Jittered cooldown (16-63 cycles)
                    int_cooldown_target <= {int_lfsr[5:4], 4'h0} + 6'h10;
                end

                INT_COOLDOWN: begin
                    int_counter <= int_counter + 1'b1;
                    if (int_counter >= int_cooldown_target)
                        int_state <= INT_IDLE;
                end
            endcase
        end
    end
{{ end }}

    // ========================================================================
    // Reset and Write Logic
    // ========================================================================

    always @(posedge clk) begin
        if (rst) begin
{{ range .BARModel.Registers }}            reg_0x{{ hex08 .Offset }} <= {{ mul .Width 8 }}'h{{ hex08 .Reset }};
{{ end }}        end
        else if (wr_valid) begin
            case (wr_addr[31:0] & 32'hFFFFFFFC)
{{ range .BARModel.Registers }}{{ if ne .RWMask 0 }}                32'h{{ hex08 (alignedOffset .Offset) }}: begin
                    if (wr_be[0]) reg_0x{{ hex08 .Offset }}[7:0]   <= (reg_0x{{ hex08 .Offset }}[7:0]   & ~8'h{{ hex02 (index (rwMaskBytes .RWMask) 0) }}) | (wr_data[7:0]   & 8'h{{ hex02 (index (rwMaskBytes .RWMask) 0) }});
                    if (wr_be[1]) reg_0x{{ hex08 .Offset }}[15:8]  <= (reg_0x{{ hex08 .Offset }}[15:8]  & ~8'h{{ hex02 (index (rwMaskBytes .RWMask) 1) }}) | (wr_data[15:8]  & 8'h{{ hex02 (index (rwMaskBytes .RWMask) 1) }});
                    if (wr_be[2]) reg_0x{{ hex08 .Offset }}[23:16] <= (reg_0x{{ hex08 .Offset }}[23:16] & ~8'h{{ hex02 (index (rwMaskBytes .RWMask) 2) }}) | (wr_data[23:16] & 8'h{{ hex02 (index (rwMaskBytes .RWMask) 2) }});
                    if (wr_be[3]) reg_0x{{ hex08 .Offset }}[31:24] <= (reg_0x{{ hex08 .Offset }}[31:24] & ~8'h{{ hex02 (index (rwMaskBytes .RWMask) 3) }}) | (wr_data[31:24] & 8'h{{ hex02 (index (rwMaskBytes .RWMask) 3) }});
                end
{{ end }}{{ end }}                default: begin
                    // unregistered offset — ignore write
                end
            endcase
        end
    end

    // ========================================================================
    // Read Logic (2-cycle latency)
    // ========================================================================

    reg [87:0] rd_req_ctx_d1;
    reg        rd_req_valid_d1;
    reg [31:0] rd_data_d1;

    always @(posedge clk) begin
        rd_req_ctx_d1   <= rd_req_ctx;
        rd_req_valid_d1 <= rd_req_valid;

        if (rd_req_valid) begin
            case (rd_req_addr[31:0] & 32'hFFFFFFFC)
{{ range .BARModel.Registers }}                32'h{{ hex08 (alignedOffset .Offset) }}: rd_data_d1 <= reg_0x{{ hex08 .Offset }};
{{ end }}                default: rd_data_d1 <= 32'h00000000;
            endcase
        end
        else begin
            rd_data_d1 <= 32'h00000000;
        end
    end

    always @(posedge clk) begin
        rd_rsp_ctx   <= rd_req_ctx_d1;
        rd_rsp_valid <= rd_req_valid_d1;
        rd_rsp_data  <= rd_data_d1;
    end

{{ else }}
// No learned register map — fallback to BRAM-based storage.
module pcileech_bar_impl_device #(
    parameter BAR_SIZE = 4096
)(
    input               rst,
    input               clk,

    input [31:0]        wr_addr,
    input [31:0]        wr_data,
    input [3:0]         wr_be,
    input               wr_valid,

    input [87:0]        rd_req_ctx,
    input [31:0]        rd_req_addr,
    input               rd_req_valid,

    output reg [87:0]   rd_rsp_ctx,
    output reg [31:0]   rd_rsp_data,
    output reg          rd_rsp_valid
);

    reg [87:0] rd_req_ctx_d1;
    reg        rd_req_valid_d1;
    wire [31:0] doutb;

    always @(posedge clk) begin
        rd_req_ctx_d1   <= rd_req_ctx;
        rd_req_valid_d1 <= rd_req_valid;
        rd_rsp_ctx      <= rd_req_ctx_d1;
        rd_rsp_valid    <= rd_req_valid_d1;
        rd_rsp_data     <= doutb;
    end

    bram_bar_zero4k i_bram_bar_fallback(
        .addra  ( wr_addr[11:2]     ),
        .clka   ( clk               ),
        .dina   ( wr_data           ),
        .ena    ( wr_valid          ),
        .wea    ( wr_be             ),
        .addrb  ( rd_req_addr[11:2] ),
        .clkb   ( clk               ),
        .doutb  ( doutb             ),
        .enb    ( rd_req_valid      )
    );

{{ end }}
endmodule
`

var barControllerTmpl = `//
// PCILeech FPGA - Device-Aware BAR Controller
//
// Auto-generated by PCILeechGen
// Device: {{ hex04 .DeviceIDs.VendorID }}:{{ hex04 .DeviceIDs.DeviceID }}
//
// Based on PCILeech FPGA BAR PIO controller by Ulf Frisk.
// Modified to use device-specific BAR implementation when available.
{{ if .LatencyConfig }}// TLP latency emulation: min={{ .LatencyConfig.MinCycles }}, max={{ .LatencyConfig.MaxCycles }}, avg={{ .LatencyConfig.AvgCycles }}
{{ end }}//

` + "`" + `timescale 1ns / 1ps
` + "`" + `include "pcileech_header.svh"

module pcileech_tlps128_bar_controller(
    input                   rst,
    input                   clk,
    input                   bar_en,
    input [15:0]            pcie_id,
    IfAXIS128.sink_lite     tlps_in,
    IfAXIS128.source        tlps_out
);

    // ------------------------------------------------------------------------
    // TLP receive: incoming BAR requests → read/write FIFOs
    // ------------------------------------------------------------------------
    wire in_is_wr_ready;
    bit  in_is_wr_last;
    wire in_is_first    = tlps_in.tuser[0];
    wire in_is_bar      = bar_en && (tlps_in.tuser[8:2] != 0);
    wire in_is_rd       = (in_is_first && tlps_in.tlast && ((tlps_in.tdata[31:25] == 7'b0000000) || (tlps_in.tdata[31:25] == 7'b0010000) || (tlps_in.tdata[31:24] == 8'b00000010)));
    wire in_is_wr       = in_is_wr_last || (in_is_first && in_is_wr_ready && ((tlps_in.tdata[31:25] == 7'b0100000) || (tlps_in.tdata[31:25] == 7'b0110000) || (tlps_in.tdata[31:24] == 8'b01000010)));

    always @ ( posedge clk )
        if ( rst ) begin
            in_is_wr_last <= 0;
        end
        else if ( tlps_in.tvalid ) begin
            in_is_wr_last <= !tlps_in.tlast && in_is_wr;
        end

    wire [6:0]  wr_bar;
    wire [31:0] wr_addr;
    wire [3:0]  wr_be;
    wire [31:0] wr_data;
    wire        wr_valid;
    wire [87:0] rd_req_ctx;
    wire [6:0]  rd_req_bar;
    wire [31:0] rd_req_addr;
    wire        rd_req_valid;
    wire [87:0] rd_rsp_ctx;
    wire [31:0] rd_rsp_data;
    wire        rd_rsp_valid;

    pcileech_tlps128_bar_rdengine i_pcileech_tlps128_bar_rdengine(
        .rst            ( rst                           ),
        .clk            ( clk                           ),
        .pcie_id        ( pcie_id                       ),
        .tlps_in        ( tlps_in                       ),
        .tlps_in_valid  ( tlps_in.tvalid && in_is_bar && in_is_rd ),
        .tlps_out       ( tlps_out                      ),
        .rd_req_ctx     ( rd_req_ctx                    ),
        .rd_req_bar     ( rd_req_bar                    ),
        .rd_req_addr    ( rd_req_addr                   ),
        .rd_req_valid   ( rd_req_valid                  ),
        .rd_rsp_ctx     ( rd_rsp_ctx                    ),
        .rd_rsp_data    ( rd_rsp_data                   ),
        .rd_rsp_valid   ( rd_rsp_valid                  )
    );

    pcileech_tlps128_bar_wrengine i_pcileech_tlps128_bar_wrengine(
        .rst            ( rst                           ),
        .clk            ( clk                           ),
        .tlps_in        ( tlps_in                       ),
        .tlps_in_valid  ( tlps_in.tvalid && in_is_bar && in_is_wr ),
        .tlps_in_ready  ( in_is_wr_ready                ),
        .wr_bar         ( wr_bar                        ),
        .wr_addr        ( wr_addr                       ),
        .wr_be          ( wr_be                         ),
        .wr_data        ( wr_data                       ),
        .wr_valid       ( wr_valid                      )
    );

{{ if .LatencyConfig }}
    // BAR0 raw response wires (before latency emulation)
    wire [87:0] bar0_raw_ctx;
    wire [31:0] bar0_raw_data;
    wire        bar0_raw_valid;

    // latency emulated response
    wire [87:0] bar0_emu_ctx;
    wire [31:0] bar0_emu_data;
    wire        bar0_emu_valid;
    wire        bar0_emu_ready = 1'b1;
{{ end }}

    wire [87:0] bar_rsp_ctx[7];
    wire [31:0] bar_rsp_data[7];
    wire        bar_rsp_valid[7];

{{ if .LatencyConfig }}
    assign bar_rsp_ctx[0]   = bar0_emu_ctx;
    assign bar_rsp_data[0]  = bar0_emu_data;
    assign bar_rsp_valid[0] = bar0_emu_valid;
{{ end }}

    // response mux
    assign rd_rsp_ctx = bar_rsp_valid[0] ? bar_rsp_ctx[0] :
                        bar_rsp_valid[1] ? bar_rsp_ctx[1] :
                        bar_rsp_valid[2] ? bar_rsp_ctx[2] :
                        bar_rsp_valid[3] ? bar_rsp_ctx[3] :
                        bar_rsp_valid[4] ? bar_rsp_ctx[4] :
                        bar_rsp_valid[5] ? bar_rsp_ctx[5] :
                        bar_rsp_valid[6] ? bar_rsp_ctx[6] : 0;
    assign rd_rsp_data = bar_rsp_valid[0] ? bar_rsp_data[0] :
                        bar_rsp_valid[1] ? bar_rsp_data[1] :
                        bar_rsp_valid[2] ? bar_rsp_data[2] :
                        bar_rsp_valid[3] ? bar_rsp_data[3] :
                        bar_rsp_valid[4] ? bar_rsp_data[4] :
                        bar_rsp_valid[5] ? bar_rsp_data[5] :
                        bar_rsp_valid[6] ? bar_rsp_data[6] : 0;
    assign rd_rsp_valid = bar_rsp_valid[0] || bar_rsp_valid[1] || bar_rsp_valid[2] || bar_rsp_valid[3] || bar_rsp_valid[4] || bar_rsp_valid[5] || bar_rsp_valid[6];

    // ========================================================================
    // BAR0: {{ if .BARModel }}Device-specific implementation{{ else }}Generic zerowrite4k{{ end }}
    // ========================================================================

{{ if .BARModel }}
    pcileech_bar_impl_device #(
        .BAR_SIZE       ( {{ .BARModel.Size }} )
    ) i_bar0(
{{ else }}
    pcileech_bar_impl_zerowrite4k i_bar0(
{{ end }}
        .rst            ( rst                           ),
        .clk            ( clk                           ),
        .wr_addr        ( wr_addr                       ),
        .wr_be          ( wr_be                         ),
        .wr_data        ( wr_data                       ),
        .wr_valid       ( wr_valid && wr_bar[0]         ),
        .rd_req_ctx     ( rd_req_ctx                    ),
        .rd_req_addr    ( rd_req_addr                   ),
        .rd_req_valid   ( rd_req_valid && rd_req_bar[0] ),
{{ if .LatencyConfig }}
        .rd_rsp_ctx     ( bar0_raw_ctx                  ),
        .rd_rsp_data    ( bar0_raw_data                 ),
        .rd_rsp_valid   ( bar0_raw_valid                )
{{ else }}
        .rd_rsp_ctx     ( bar_rsp_ctx[0]                ),
        .rd_rsp_data    ( bar_rsp_data[0]               ),
        .rd_rsp_valid   ( bar_rsp_valid[0]              )
{{ end }}
    );

{{ if .LatencyConfig }}
    // Latency emulator on BAR0 responses
    tlp_latency_emulator i_latency_emu(
        .clk            ( clk                           ),
        .rst            ( rst                           ),
        .req_valid      ( bar0_raw_valid                ),
        .req_ctx        ( bar0_raw_ctx                  ),
        .req_data       ( bar0_raw_data                 ),
        .req_addr       ( rd_req_addr                   ),
        .req_ready      (                               ),
        .rsp_valid      ( bar0_emu_valid                ),
        .rsp_ctx        ( bar0_emu_ctx                  ),
        .rsp_data       ( bar0_emu_data                 ),
        .rsp_ready      ( bar0_emu_ready                )
    );
{{ end }}

    // BAR1: address loopback
    pcileech_bar_impl_loopaddr i_bar1(
        .rst            ( rst                           ),
        .clk            ( clk                           ),
        .wr_addr        ( wr_addr                       ),
        .wr_be          ( wr_be                         ),
        .wr_data        ( wr_data                       ),
        .wr_valid       ( wr_valid && wr_bar[1]         ),
        .rd_req_ctx     ( rd_req_ctx                    ),
        .rd_req_addr    ( rd_req_addr                   ),
        .rd_req_valid   ( rd_req_valid && rd_req_bar[1] ),
        .rd_rsp_ctx     ( bar_rsp_ctx[1]                ),
        .rd_rsp_data    ( bar_rsp_data[1]               ),
        .rd_rsp_valid   ( bar_rsp_valid[1]              )
    );

    // BAR2-6: unimplemented
    genvar gi;
    generate
        for (gi = 2; gi < 7; gi = gi + 1) begin : gen_bar_none
            pcileech_bar_impl_none i_bar_none(
                .rst            ( rst                           ),
                .clk            ( clk                           ),
                .wr_addr        ( wr_addr                       ),
                .wr_be          ( wr_be                         ),
                .wr_data        ( wr_data                       ),
                .wr_valid       ( wr_valid && wr_bar[gi]        ),
                .rd_req_ctx     ( rd_req_ctx                    ),
                .rd_req_addr    ( rd_req_addr                   ),
                .rd_req_valid   ( rd_req_valid && rd_req_bar[gi]),
                .rd_rsp_ctx     ( bar_rsp_ctx[gi]               ),
                .rd_rsp_data    ( bar_rsp_data[gi]              ),
                .rd_rsp_valid   ( bar_rsp_valid[gi]             )
            );
        end
    endgenerate

endmodule
`

var deviceConfigTmpl = `//
// PCILeech Device Configuration
//
// Auto-generated by PCILeechGen
// This file contains device identity and configuration parameters.
//

// Device Identity
// Vendor ID:       0x{{ hex04 .DeviceIDs.VendorID }}
// Device ID:       0x{{ hex04 .DeviceIDs.DeviceID }}
// Subsys Vendor:   0x{{ hex04 .DeviceIDs.SubsysVendorID }}
// Subsys Device:   0x{{ hex04 .DeviceIDs.SubsysDeviceID }}
// Revision:        0x{{ hex02 .DeviceIDs.RevisionID }}
// Class Code:      0x{{ hex02 (classBase .ClassCode) }}{{ hex02 (classSub .ClassCode) }}{{ hex02 (classProgIF .ClassCode) }}
{{ if .DeviceIDs.HasDSN }}// DSN:             0x{{ printf "%016X" .DeviceIDs.DSN }}{{ end }}
{{ if .DeviceIDs.HasPCIeCap }}// PCIe Link:       Speed={{ .DeviceIDs.LinkSpeed }} Width=x{{ .DeviceIDs.LinkWidth }}{{ end }}
//
// Features:
{{ if .IsNVMe }}//   - NVMe CC→CSTS state machine (dynamic handshake)
{{ end }}{{ if .IsXHCI }}//   - xHCI USBCMD/USBSTS state machine
{{ end }}{{ if .HasMSIX }}//   - MSI-X interrupt controller
{{ end }}{{ if .LatencyConfig }}//   - TLP latency emulation (min={{ .LatencyConfig.MinCycles }}, max={{ .LatencyConfig.MaxCycles }}, avg={{ .LatencyConfig.AvgCycles }})
{{ end }}

` + "`" + `ifndef DEVICE_CONFIG_SV
` + "`" + `define DEVICE_CONFIG_SV

package device_config;
    localparam VENDOR_ID        = 16'h{{ hex04 .DeviceIDs.VendorID }};
    localparam DEVICE_ID        = 16'h{{ hex04 .DeviceIDs.DeviceID }};
    localparam SUBSYS_VENDOR_ID = 16'h{{ hex04 .DeviceIDs.SubsysVendorID }};
    localparam SUBSYS_DEVICE_ID = 16'h{{ hex04 .DeviceIDs.SubsysDeviceID }};
    localparam REVISION_ID      = 8'h{{ hex02 .DeviceIDs.RevisionID }};
    localparam CLASS_BASE       = 8'h{{ hex02 (classBase .ClassCode) }};
    localparam CLASS_SUB        = 8'h{{ hex02 (classSub .ClassCode) }};
    localparam CLASS_PROGIF     = 8'h{{ hex02 (classProgIF .ClassCode) }};
{{ if .BARModel }}
    // BAR0 is device-specific ({{ .BARModel.Size }} bytes, {{ len .BARModel.Registers }} registers)
    localparam BAR0_SIZE        = {{ .BARModel.Size }};
    localparam BAR0_REGS        = {{ len .BARModel.Registers }};
{{ else }}
    // BAR0 uses generic zerowrite4k implementation
    localparam BAR0_SIZE        = 4096;
    localparam BAR0_REGS        = 0;
{{ end }}
{{ if .LatencyConfig }}
    // TLP Latency Emulation
    localparam LATENCY_MIN      = {{ .LatencyConfig.MinCycles }};
    localparam LATENCY_MAX      = {{ .LatencyConfig.MaxCycles }};
    localparam LATENCY_AVG      = {{ .LatencyConfig.AvgCycles }};
{{ end }}
    // Feature flags
    localparam HAS_NVME_FSM     = {{ if .IsNVMe }}1{{ else }}0{{ end }};
    localparam HAS_XHCI_FSM     = {{ if .IsXHCI }}1{{ else }}0{{ end }};
    localparam HAS_MSIX_INT     = {{ if .HasMSIX }}1{{ else }}0{{ end }};
    localparam HAS_LATENCY_EMU  = {{ if .LatencyConfig }}1{{ else }}0{{ end }};
endpackage

` + "`" + `endif // DEVICE_CONFIG_SV
`
