// Verilated -*- C++ -*-
// DESCRIPTION: Verilator output: Design internal header
// See Vtop.h for the primary calling header

#ifndef VERILATED_VTOP___024ROOT_H_
#define VERILATED_VTOP___024ROOT_H_  // guard

#include "verilated.h"
#include "verilated_timing.h"
class Vtop_IfAXIS128;
class Vtop_device_config;


class Vtop__Syms;

class alignas(VL_CACHE_LINE_BYTES) Vtop___024root final {
  public:
    // CELLS
    Vtop_device_config* __PVT__device_config;
    Vtop_IfAXIS128* __PVT__tb_top__DOT__tlps_in_if;
    Vtop_IfAXIS128* __PVT__tb_top__DOT__tlps_out_if;
    Vtop_IfAXIS128* __PVT__tb_top__DOT__tlps_dma_out_if;
    Vtop_IfAXIS128* __PVT__tb_top__DOT__i_bar__DOT__tlps_rdeng;
    Vtop_IfAXIS128* __PVT__tb_top__DOT__i_bar__DOT__tlps_ur;
    Vtop_IfAXIS128* __PVT__tb_top__DOT__i_bar__DOT__tlps_cpl;

    // DESIGN SPECIFIC STATE
    // Anonymous structures to workaround compiler member-count bugs
    struct {
        CData/*0:0*/ tb_top__DOT__clk;
        CData/*0:0*/ tb_top__DOT__rst;
        CData/*1:0*/ tb_top__DOT__cfg_power_state;
        CData/*0:0*/ tb_top__DOT__cfg_flr_in_process;
        CData/*0:0*/ tb_top__DOT__cfg_to_turnoff;
        CData/*0:0*/ tb_top__DOT__cfg_link_up;
        CData/*0:0*/ tb_top__DOT__cfg_msi_enable;
        CData/*0:0*/ tb_top__DOT__cfg_msix_enable;
        CData/*0:0*/ tb_top__DOT__cfg_msix_function_mask;
        CData/*0:0*/ tb_top__DOT__bar_en;
        CData/*3:0*/ tb_top__DOT__tlps_in_tkeepdw;
        CData/*0:0*/ tb_top__DOT__tlps_in_tvalid;
        CData/*0:0*/ tb_top__DOT__tlps_in_tlast;
        CData/*3:0*/ tb_top__DOT__tlps_out_tkeepdw;
        CData/*0:0*/ tb_top__DOT__tlps_out_tvalid;
        CData/*0:0*/ tb_top__DOT__tlps_out_tlast;
        CData/*0:0*/ tb_top__DOT__tlps_out_has_data;
        CData/*0:0*/ tb_top__DOT__tlps_dma_out_tvalid;
        CData/*0:0*/ tb_top__DOT__intr_req;
        CData/*0:0*/ tb_top__DOT__i_bar__DOT__rst;
        CData/*0:0*/ tb_top__DOT__i_bar__DOT__clk;
        CData/*0:0*/ tb_top__DOT__i_bar__DOT__bar_en;
        CData/*1:0*/ tb_top__DOT__i_bar__DOT__cfg_power_state;
        CData/*0:0*/ tb_top__DOT__i_bar__DOT__cfg_flr_in_process;
        CData/*0:0*/ tb_top__DOT__i_bar__DOT__cfg_to_turnoff;
        CData/*0:0*/ tb_top__DOT__i_bar__DOT__cfg_link_up;
        CData/*0:0*/ tb_top__DOT__i_bar__DOT__cfg_msi_enable;
        CData/*0:0*/ tb_top__DOT__i_bar__DOT__cfg_msix_enable;
        CData/*0:0*/ tb_top__DOT__i_bar__DOT__cfg_msix_function_mask;
        CData/*0:0*/ tb_top__DOT__i_bar__DOT__flash_csn;
        CData/*0:0*/ tb_top__DOT__i_bar__DOT__flash_sdi_dq0;
        CData/*0:0*/ tb_top__DOT__i_bar__DOT__flash_sdo_dq1;
        CData/*0:0*/ tb_top__DOT__i_bar__DOT__flash_wpn_dq2;
        CData/*0:0*/ tb_top__DOT__i_bar__DOT__flash_hldn_dq3;
        CData/*0:0*/ tb_top__DOT__i_bar__DOT__intr_req;
        CData/*0:0*/ tb_top__DOT__i_bar__DOT__cfg_mse;
        CData/*0:0*/ tb_top__DOT__i_bar__DOT__cfg_bme;
        CData/*0:0*/ tb_top__DOT__i_bar__DOT__device_reset;
        CData/*0:0*/ tb_top__DOT__i_bar__DOT__io_enabled;
        CData/*0:0*/ tb_top__DOT__i_bar__DOT__dma_enabled;
        CData/*0:0*/ tb_top__DOT__i_bar__DOT__lifecycle_quiesce;
        CData/*0:0*/ tb_top__DOT__i_bar__DOT__in_is_wr_ready;
        CData/*0:0*/ tb_top__DOT__i_bar__DOT__in_is_wr_last;
        CData/*0:0*/ tb_top__DOT__i_bar__DOT__in_is_bar;
        CData/*0:0*/ tb_top__DOT__i_bar__DOT__norm_request_present;
        CData/*0:0*/ tb_top__DOT__i_bar__DOT__norm_request_supported;
        CData/*0:0*/ tb_top__DOT__i_bar__DOT__norm_unsupported_request;
        CData/*0:0*/ tb_top__DOT__i_bar__DOT__norm_ur_required;
        CData/*0:0*/ tb_top__DOT__i_bar__DOT__norm_non_posted_request;
        CData/*0:0*/ tb_top__DOT__i_bar__DOT__norm_malformed_request;
        CData/*0:0*/ tb_top__DOT__i_bar__DOT__norm_posted_write;
        CData/*0:0*/ tb_top__DOT__i_bar__DOT__norm_memory_read;
        CData/*0:0*/ tb_top__DOT__i_bar__DOT__norm_memory_write;
        CData/*2:0*/ tb_top__DOT__i_bar__DOT__norm_request_kind;
        CData/*0:0*/ tb_top__DOT__i_bar__DOT__norm_header_4dw;
        CData/*3:0*/ tb_top__DOT__i_bar__DOT__norm_first_be;
        CData/*3:0*/ tb_top__DOT__i_bar__DOT__norm_last_be;
        CData/*7:0*/ tb_top__DOT__i_bar__DOT__norm_tag;
        CData/*2:0*/ tb_top__DOT__i_bar__DOT__norm_traffic_class;
        CData/*2:0*/ tb_top__DOT__i_bar__DOT__norm_attributes;
        CData/*2:0*/ tb_top__DOT__i_bar__DOT__norm_bir;
        CData/*6:0*/ tb_top__DOT__i_bar__DOT__norm_bar_mask;
        CData/*6:0*/ tb_top__DOT__i_bar__DOT__norm_first_lower_address;
        CData/*0:0*/ tb_top__DOT__i_bar__DOT__in_is_first;
    };
    struct {
        CData/*0:0*/ tb_top__DOT__i_bar__DOT__in_is_rd;
        CData/*0:0*/ tb_top__DOT__i_bar__DOT__in_is_wr;
        CData/*6:0*/ tb_top__DOT__i_bar__DOT__wr_bar;
        CData/*3:0*/ tb_top__DOT__i_bar__DOT__wr_be;
        CData/*0:0*/ tb_top__DOT__i_bar__DOT__wr_valid;
        CData/*6:0*/ tb_top__DOT__i_bar__DOT__rd_req_bar;
        CData/*0:0*/ tb_top__DOT__i_bar__DOT__rd_req_valid;
        CData/*0:0*/ tb_top__DOT__i_bar__DOT__rd_rsp_valid;
        CData/*0:0*/ tb_top__DOT__i_bar__DOT__bar0_wr_hit;
        CData/*0:0*/ tb_top__DOT__i_bar__DOT__bar0_rd_hit;
        CData/*0:0*/ tb_top__DOT__i_bar__DOT__ur_request_ready;
        CData/*0:0*/ tb_top__DOT__i_bar__DOT__ur_request_pending;
        CData/*7:0*/ tb_top__DOT__i_bar__DOT__ur_request_read_ptr;
        CData/*7:0*/ tb_top__DOT__i_bar__DOT__ur_request_write_ptr;
        CData/*0:0*/ tb_top__DOT__i_bar__DOT__ur_request_dequeue;
        CData/*0:0*/ tb_top__DOT__i_bar__DOT__ur_request_enqueue;
        CData/*0:0*/ tb_top__DOT__i_bar__DOT__cpl_grant_active;
        CData/*0:0*/ tb_top__DOT__i_bar__DOT__cpl_grant_ur;
        CData/*0:0*/ tb_top__DOT__i_bar__DOT__cpl_rr_ur;
        CData/*0:0*/ tb_top__DOT__i_bar__DOT__cpl_select_ur;
        CData/*0:0*/ tb_top__DOT__i_bar__DOT__cpl_selected_valid;
        CData/*0:0*/ tb_top__DOT__i_bar__DOT__cpl_selected_last;
        CData/*0:0*/ tb_top__DOT__i_bar__DOT__wrengine_ready;
        CData/*0:0*/ tb_top__DOT__i_bar__DOT__bar0_wr_ack;
        CData/*0:0*/ tb_top__DOT__i_bar__DOT__hda_crst_falling;
        CData/*0:0*/ tb_top__DOT__i_bar__DOT__bar0_raw_valid;
        CData/*0:0*/ tb_top__DOT__i_bar__DOT__bar0_emu_valid;
        CData/*0:0*/ tb_top__DOT__i_bar__DOT__bar0_emu_busy;
        CData/*0:0*/ tb_top__DOT__i_bar__DOT__bar0_emu_ready;
        CData/*0:0*/ tb_top__DOT__i_bar__DOT__bar0_emu_busy_d1;
        CData/*0:0*/ tb_top__DOT__i_bar__DOT__bar0_emu_accepted;
        CData/*4:0*/ tb_top__DOT__i_bar__DOT__bar0_buf_count;
        CData/*3:0*/ tb_top__DOT__i_bar__DOT__bar0_buf_rd;
        CData/*3:0*/ tb_top__DOT__i_bar__DOT__bar0_buf_wr;
        CData/*0:0*/ tb_top__DOT__i_bar__DOT__bar0_buf_full;
        CData/*0:0*/ tb_top__DOT__i_bar__DOT__bar0_buf_empty;
        CData/*0:0*/ tb_top__DOT__i_bar__DOT__bar0_buf_almost_full;
        CData/*0:0*/ tb_top__DOT__i_bar__DOT__bar0_buf_pop;
        CData/*0:0*/ tb_top__DOT__i_bar__DOT__bar0_spill_valid;
        CData/*0:0*/ tb_top__DOT__i_bar__DOT__bar0_buf_write;
        CData/*6:0*/ tb_top__DOT__i_bar__DOT__bar_base_valid;
        CData/*6:0*/ tb_top__DOT__i_bar__DOT__bar_rsp_valid;
        CData/*0:0*/ tb_top__DOT__i_bar__DOT__bar0_base_valid;
        CData/*6:0*/ tb_top__DOT__i_bar__DOT__bar_rsp_ready;
        CData/*0:0*/ tb_top__DOT__i_bar__DOT____Vcellinp__i_bar0__wr_valid;
        CData/*0:0*/ tb_top__DOT__i_bar__DOT__i_lifecycle_service__DOT__clk;
        CData/*0:0*/ tb_top__DOT__i_bar__DOT__i_lifecycle_service__DOT__fundamental_reset;
        CData/*0:0*/ tb_top__DOT__i_bar__DOT__i_lifecycle_service__DOT__flr_in_process;
        CData/*1:0*/ tb_top__DOT__i_bar__DOT__i_lifecycle_service__DOT__pm_dstate;
        CData/*0:0*/ tb_top__DOT__i_bar__DOT__i_lifecycle_service__DOT__memory_space_enable;
        CData/*0:0*/ tb_top__DOT__i_bar__DOT__i_lifecycle_service__DOT__bus_master_enable;
        CData/*0:0*/ tb_top__DOT__i_bar__DOT__i_lifecycle_service__DOT__turnoff_pending;
        CData/*0:0*/ tb_top__DOT__i_bar__DOT__i_lifecycle_service__DOT__link_up;
        CData/*0:0*/ tb_top__DOT__i_bar__DOT__i_lifecycle_service__DOT__device_reset;
        CData/*0:0*/ tb_top__DOT__i_bar__DOT__i_lifecycle_service__DOT__io_enabled;
        CData/*0:0*/ tb_top__DOT__i_bar__DOT__i_lifecycle_service__DOT__dma_enabled;
        CData/*0:0*/ tb_top__DOT__i_bar__DOT__i_lifecycle_service__DOT__quiesce;
        CData/*0:0*/ tb_top__DOT__i_bar__DOT__i_lifecycle_service__DOT__active;
        CData/*0:0*/ tb_top__DOT__i_bar__DOT__i_lifecycle_service__DOT__reset_d;
        CData/*2:0*/ tb_top__DOT__i_bar__DOT__i_tlp_normalizer__DOT____VlemCall_5__popcount4;
        CData/*2:0*/ tb_top__DOT__i_bar__DOT__i_tlp_normalizer__DOT____VlemCall_4__popcount4;
        CData/*2:0*/ tb_top__DOT__i_bar__DOT__i_tlp_normalizer__DOT____VlemCall_3__popcount4;
        CData/*0:0*/ tb_top__DOT__i_bar__DOT__i_tlp_normalizer__DOT____VlemCond_2;
        CData/*0:0*/ tb_top__DOT__i_bar__DOT__i_tlp_normalizer__DOT____VlemCall_1__valid_last_edge;
    };
    struct {
        CData/*0:0*/ tb_top__DOT__i_bar__DOT__i_tlp_normalizer__DOT____VlemCall_0__valid_first_edge;
        CData/*0:0*/ tb_top__DOT__i_bar__DOT__i_tlp_normalizer__DOT__tlp_last;
        CData/*0:0*/ tb_top__DOT__i_bar__DOT__i_tlp_normalizer__DOT__request_present;
        CData/*0:0*/ tb_top__DOT__i_bar__DOT__i_tlp_normalizer__DOT__request_supported;
        CData/*0:0*/ tb_top__DOT__i_bar__DOT__i_tlp_normalizer__DOT__unsupported_request;
        CData/*0:0*/ tb_top__DOT__i_bar__DOT__i_tlp_normalizer__DOT__ur_required;
        CData/*0:0*/ tb_top__DOT__i_bar__DOT__i_tlp_normalizer__DOT__non_posted_request;
        CData/*0:0*/ tb_top__DOT__i_bar__DOT__i_tlp_normalizer__DOT__malformed_request;
        CData/*0:0*/ tb_top__DOT__i_bar__DOT__i_tlp_normalizer__DOT__posted_write;
        CData/*0:0*/ tb_top__DOT__i_bar__DOT__i_tlp_normalizer__DOT__memory_read;
        CData/*0:0*/ tb_top__DOT__i_bar__DOT__i_tlp_normalizer__DOT__memory_write;
        CData/*2:0*/ tb_top__DOT__i_bar__DOT__i_tlp_normalizer__DOT__request_kind;
        CData/*0:0*/ tb_top__DOT__i_bar__DOT__i_tlp_normalizer__DOT__header_4dw;
        CData/*3:0*/ tb_top__DOT__i_bar__DOT__i_tlp_normalizer__DOT__first_be;
        CData/*3:0*/ tb_top__DOT__i_bar__DOT__i_tlp_normalizer__DOT__last_be;
        CData/*7:0*/ tb_top__DOT__i_bar__DOT__i_tlp_normalizer__DOT__tag;
        CData/*2:0*/ tb_top__DOT__i_bar__DOT__i_tlp_normalizer__DOT__traffic_class;
        CData/*2:0*/ tb_top__DOT__i_bar__DOT__i_tlp_normalizer__DOT__attributes;
        CData/*2:0*/ tb_top__DOT__i_bar__DOT__i_tlp_normalizer__DOT__bir;
        CData/*6:0*/ tb_top__DOT__i_bar__DOT__i_tlp_normalizer__DOT__bar_mask;
        CData/*6:0*/ tb_top__DOT__i_bar__DOT__i_tlp_normalizer__DOT__first_lower_address;
        CData/*2:0*/ tb_top__DOT__i_bar__DOT__i_tlp_normalizer__DOT__fmt;
        CData/*4:0*/ tb_top__DOT__i_bar__DOT__i_tlp_normalizer__DOT__tlp_type;
        CData/*0:0*/ tb_top__DOT__i_bar__DOT__i_tlp_normalizer__DOT__legal_be;
        CData/*0:0*/ tb_top__DOT__i_bar__DOT__i_tlp_normalizer__DOT__legal_bar;
        CData/*0:0*/ tb_top__DOT__i_bar__DOT__i_tlp_normalizer__DOT__crosses_4k;
        CData/*0:0*/ tb_top__DOT__i_bar__DOT__i_pcileech_tlps128_bar_rdengine__DOT__rst;
        CData/*0:0*/ tb_top__DOT__i_bar__DOT__i_pcileech_tlps128_bar_rdengine__DOT__clk;
        CData/*0:0*/ tb_top__DOT__i_bar__DOT__i_pcileech_tlps128_bar_rdengine__DOT__stall;
        CData/*0:0*/ tb_top__DOT__i_bar__DOT__i_pcileech_tlps128_bar_rdengine__DOT__tlps_in_valid;
        CData/*3:0*/ tb_top__DOT__i_bar__DOT__i_pcileech_tlps128_bar_rdengine__DOT__norm_first_be;
        CData/*3:0*/ tb_top__DOT__i_bar__DOT__i_pcileech_tlps128_bar_rdengine__DOT__norm_last_be;
        CData/*7:0*/ tb_top__DOT__i_bar__DOT__i_pcileech_tlps128_bar_rdengine__DOT__norm_tag;
        CData/*2:0*/ tb_top__DOT__i_bar__DOT__i_pcileech_tlps128_bar_rdengine__DOT__norm_traffic_class;
        CData/*2:0*/ tb_top__DOT__i_bar__DOT__i_pcileech_tlps128_bar_rdengine__DOT__norm_attributes;
        CData/*0:0*/ tb_top__DOT__i_bar__DOT__i_pcileech_tlps128_bar_rdengine__DOT__norm_header_4dw;
        CData/*6:0*/ tb_top__DOT__i_bar__DOT__i_pcileech_tlps128_bar_rdengine__DOT__norm_bar_mask;
        CData/*6:0*/ tb_top__DOT__i_bar__DOT__i_pcileech_tlps128_bar_rdengine__DOT__rd_req_bar;
        CData/*0:0*/ tb_top__DOT__i_bar__DOT__i_pcileech_tlps128_bar_rdengine__DOT__rd_req_valid;
        CData/*0:0*/ tb_top__DOT__i_bar__DOT__i_pcileech_tlps128_bar_rdengine__DOT__rd_rsp_valid;
        CData/*7:0*/ tb_top__DOT__i_bar__DOT__i_pcileech_tlps128_bar_rdengine__DOT__req_wr_ptr;
        CData/*7:0*/ tb_top__DOT__i_bar__DOT__i_pcileech_tlps128_bar_rdengine__DOT__req_rd_ptr;
        CData/*0:0*/ tb_top__DOT__i_bar__DOT__i_pcileech_tlps128_bar_rdengine__DOT__state;
        CData/*3:0*/ tb_top__DOT__i_bar__DOT__i_pcileech_tlps128_bar_rdengine__DOT__request_first_be;
        CData/*3:0*/ tb_top__DOT__i_bar__DOT__i_pcileech_tlps128_bar_rdengine__DOT__request_last_be;
        CData/*7:0*/ tb_top__DOT__i_bar__DOT__i_pcileech_tlps128_bar_rdengine__DOT__request_tag;
        CData/*2:0*/ tb_top__DOT__i_bar__DOT__i_pcileech_tlps128_bar_rdengine__DOT__request_tc;
        CData/*2:0*/ tb_top__DOT__i_bar__DOT__i_pcileech_tlps128_bar_rdengine__DOT__request_attr;
        CData/*0:0*/ tb_top__DOT__i_bar__DOT__i_pcileech_tlps128_bar_rdengine__DOT__request_4dw;
        CData/*6:0*/ tb_top__DOT__i_bar__DOT__i_pcileech_tlps128_bar_rdengine__DOT__request_bar;
        CData/*0:0*/ tb_top__DOT__i_bar__DOT__i_pcileech_tlps128_bar_rdengine__DOT__request_first_packet;
        CData/*0:0*/ tb_top__DOT__i_bar__DOT__i_pcileech_tlps128_bar_rdengine__DOT__packet_first;
        CData/*0:0*/ tb_top__DOT__i_bar__DOT__i_pcileech_tlps128_bar_rdengine__DOT__request_fifo_full;
        CData/*0:0*/ tb_top__DOT__i_bar__DOT__i_pcileech_tlps128_bar_rdengine__DOT__request_pop;
        CData/*0:0*/ tb_top__DOT__i_bar__DOT__i_pcileech_tlps128_bar_rdengine__DOT__request_can_accept;
        CData/*0:0*/ tb_top__DOT__i_bar__DOT__i_pcileech_tlps128_bar_rdengine__DOT__request_push;
        CData/*0:0*/ tb_top__DOT__i_bar__DOT__i_pcileech_tlps128_bar_rdengine__DOT__rd3_enable;
        CData/*0:0*/ tb_top__DOT__i_bar__DOT__i_pcileech_tlps128_bar_rdengine__DOT__issue_dw;
        CData/*0:0*/ tb_top__DOT__i_bar__DOT__i_pcileech_tlps128_bar_rdengine__DOT__packet_last;
        CData/*0:0*/ tb_top__DOT__i_bar__DOT__i_pcileech_tlps128_bar_rdengine__DOT__request_last_packet;
        CData/*3:0*/ tb_top__DOT__i_bar__DOT__i_pcileech_tlps128_bar_rdengine__DOT__packet_start_be;
        CData/*1:0*/ tb_top__DOT__i_bar__DOT__i_pcileech_tlps128_bar_rdengine__DOT__packet_first_offset;
        CData/*0:0*/ tb_top__DOT__i_bar__DOT__i_pcileech_tlps128_bar_rdengine__DOT__rd_rsp_first;
        CData/*0:0*/ tb_top__DOT__i_bar__DOT__i_pcileech_tlps128_bar_rdengine__DOT__rd_rsp_last;
    };
    struct {
        CData/*2:0*/ tb_top__DOT__i_bar__DOT__i_pcileech_tlps128_bar_rdengine__DOT__rd_rsp_tc;
        CData/*2:0*/ tb_top__DOT__i_bar__DOT__i_pcileech_tlps128_bar_rdengine__DOT__rd_rsp_attr;
        CData/*0:0*/ tb_top__DOT__i_bar__DOT__i_pcileech_tlps128_bar_rdengine__DOT__rd_rsp_4dw;
        CData/*7:0*/ tb_top__DOT__i_bar__DOT__i_pcileech_tlps128_bar_rdengine__DOT__rd_rsp_tag;
        CData/*6:0*/ tb_top__DOT__i_bar__DOT__i_pcileech_tlps128_bar_rdengine__DOT__rd_rsp_lower_addr;
        CData/*3:0*/ tb_top__DOT__i_bar__DOT__i_pcileech_tlps128_bar_rdengine__DOT__tkeepdw;
        CData/*0:0*/ tb_top__DOT__i_bar__DOT__i_pcileech_tlps128_bar_rdengine__DOT__tlast;
        CData/*0:0*/ tb_top__DOT__i_bar__DOT__i_pcileech_tlps128_bar_rdengine__DOT__first;
        CData/*0:0*/ tb_top__DOT__i_bar__DOT__i_pcileech_tlps128_bar_rdengine__DOT__tvalid;
        CData/*0:0*/ tb_top__DOT__i_bar__DOT__i_pcileech_tlps128_bar_rdengine__DOT__unused_rd_rsp_4dw;
        CData/*0:0*/ tb_top__DOT__i_bar__DOT__i_pcileech_tlps128_bar_rdengine__DOT__i_fifo_134_134_clk1_bar_rdrsp__DOT__srst;
        CData/*0:0*/ tb_top__DOT__i_bar__DOT__i_pcileech_tlps128_bar_rdengine__DOT__i_fifo_134_134_clk1_bar_rdrsp__DOT__clk;
        CData/*0:0*/ tb_top__DOT__i_bar__DOT__i_pcileech_tlps128_bar_rdengine__DOT__i_fifo_134_134_clk1_bar_rdrsp__DOT__wr_en;
        CData/*0:0*/ tb_top__DOT__i_bar__DOT__i_pcileech_tlps128_bar_rdengine__DOT__i_fifo_134_134_clk1_bar_rdrsp__DOT__rd_en;
        CData/*0:0*/ tb_top__DOT__i_bar__DOT__i_pcileech_tlps128_bar_rdengine__DOT__i_fifo_134_134_clk1_bar_rdrsp__DOT__full;
        CData/*0:0*/ tb_top__DOT__i_bar__DOT__i_pcileech_tlps128_bar_rdengine__DOT__i_fifo_134_134_clk1_bar_rdrsp__DOT__empty;
        CData/*0:0*/ tb_top__DOT__i_bar__DOT__i_pcileech_tlps128_bar_rdengine__DOT__i_fifo_134_134_clk1_bar_rdrsp__DOT__prog_empty;
        CData/*0:0*/ tb_top__DOT__i_bar__DOT__i_pcileech_tlps128_bar_rdengine__DOT__i_fifo_134_134_clk1_bar_rdrsp__DOT__prog_full;
        CData/*0:0*/ tb_top__DOT__i_bar__DOT__i_pcileech_tlps128_bar_rdengine__DOT__i_fifo_134_134_clk1_bar_rdrsp__DOT__valid;
        CData/*0:0*/ tb_top__DOT__i_bar__DOT__i_tlp_ur_completer__DOT__rst;
        CData/*0:0*/ tb_top__DOT__i_bar__DOT__i_tlp_ur_completer__DOT__clk;
        CData/*0:0*/ tb_top__DOT__i_bar__DOT__i_tlp_ur_completer__DOT__request_valid;
        CData/*0:0*/ tb_top__DOT__i_bar__DOT__i_tlp_ur_completer__DOT__request_ready;
        CData/*7:0*/ tb_top__DOT__i_bar__DOT__i_tlp_ur_completer__DOT__tag;
        CData/*2:0*/ tb_top__DOT__i_bar__DOT__i_tlp_ur_completer__DOT__traffic_class;
        CData/*2:0*/ tb_top__DOT__i_bar__DOT__i_tlp_ur_completer__DOT__attributes;
        CData/*7:0*/ tb_top__DOT__i_bar__DOT__i_tlp_ur_completer__DOT__write_ptr;
        CData/*7:0*/ tb_top__DOT__i_bar__DOT__i_tlp_ur_completer__DOT__read_ptr;
        CData/*0:0*/ tb_top__DOT__i_bar__DOT__i_tlp_ur_completer__DOT__request_fifo_full;
        CData/*0:0*/ tb_top__DOT__i_bar__DOT__i_tlp_ur_completer__DOT__request_pop;
        CData/*0:0*/ tb_top__DOT__i_bar__DOT__i_tlp_ur_completer__DOT__request_can_accept;
        CData/*0:0*/ tb_top__DOT__i_bar__DOT__i_tlp_ur_completer__DOT__request_push;
        CData/*0:0*/ tb_top__DOT__i_bar__DOT__i_pcileech_tlps128_bar_wrengine__DOT__rst;
        CData/*0:0*/ tb_top__DOT__i_bar__DOT__i_pcileech_tlps128_bar_wrengine__DOT__clk;
        CData/*0:0*/ tb_top__DOT__i_bar__DOT__i_pcileech_tlps128_bar_wrengine__DOT__tlps_in_valid;
        CData/*0:0*/ tb_top__DOT__i_bar__DOT__i_pcileech_tlps128_bar_wrengine__DOT__tlps_in_ready;
        CData/*6:0*/ tb_top__DOT__i_bar__DOT__i_pcileech_tlps128_bar_wrengine__DOT__wr_bar;
        CData/*3:0*/ tb_top__DOT__i_bar__DOT__i_pcileech_tlps128_bar_wrengine__DOT__wr_be;
        CData/*0:0*/ tb_top__DOT__i_bar__DOT__i_pcileech_tlps128_bar_wrengine__DOT__wr_valid;
        CData/*0:0*/ tb_top__DOT__i_bar__DOT__i_pcileech_tlps128_bar_wrengine__DOT__f_rd_en;
        CData/*3:0*/ tb_top__DOT__i_bar__DOT__i_pcileech_tlps128_bar_wrengine__DOT__f_tkeepdw;
        CData/*0:0*/ tb_top__DOT__i_bar__DOT__i_pcileech_tlps128_bar_wrengine__DOT__f_tvalid;
        CData/*3:0*/ tb_top__DOT__i_bar__DOT__i_pcileech_tlps128_bar_wrengine__DOT__tkeepdw;
        CData/*0:0*/ tb_top__DOT__i_bar__DOT__i_pcileech_tlps128_bar_wrengine__DOT__tlast;
        CData/*3:0*/ tb_top__DOT__i_bar__DOT__i_pcileech_tlps128_bar_wrengine__DOT__be_first;
        CData/*3:0*/ tb_top__DOT__i_bar__DOT__i_pcileech_tlps128_bar_wrengine__DOT__be_last;
        CData/*0:0*/ tb_top__DOT__i_bar__DOT__i_pcileech_tlps128_bar_wrengine__DOT__first_dw;
        CData/*3:0*/ tb_top__DOT__i_bar__DOT__i_pcileech_tlps128_bar_wrengine__DOT__state;
        CData/*0:0*/ tb_top__DOT__i_bar__DOT__i_pcileech_tlps128_bar_wrengine__DOT__i_fifo_141_141_clk1_bar_wr__DOT__srst;
        CData/*0:0*/ tb_top__DOT__i_bar__DOT__i_pcileech_tlps128_bar_wrengine__DOT__i_fifo_141_141_clk1_bar_wr__DOT__clk;
        CData/*0:0*/ tb_top__DOT__i_bar__DOT__i_pcileech_tlps128_bar_wrengine__DOT__i_fifo_141_141_clk1_bar_wr__DOT__wr_en;
        CData/*0:0*/ tb_top__DOT__i_bar__DOT__i_pcileech_tlps128_bar_wrengine__DOT__i_fifo_141_141_clk1_bar_wr__DOT__rd_en;
        CData/*0:0*/ tb_top__DOT__i_bar__DOT__i_pcileech_tlps128_bar_wrengine__DOT__i_fifo_141_141_clk1_bar_wr__DOT__full;
        CData/*0:0*/ tb_top__DOT__i_bar__DOT__i_pcileech_tlps128_bar_wrengine__DOT__i_fifo_141_141_clk1_bar_wr__DOT__empty;
        CData/*0:0*/ tb_top__DOT__i_bar__DOT__i_pcileech_tlps128_bar_wrengine__DOT__i_fifo_141_141_clk1_bar_wr__DOT__prog_empty;
        CData/*0:0*/ tb_top__DOT__i_bar__DOT__i_pcileech_tlps128_bar_wrengine__DOT__i_fifo_141_141_clk1_bar_wr__DOT__valid;
        CData/*5:0*/ tb_top__DOT__i_bar__DOT__i_bar_rsp_arbiter__DOT____Vlvbound_h9dcf22b6__3;
        CData/*5:0*/ tb_top__DOT__i_bar__DOT__i_bar_rsp_arbiter__DOT____Vlvbound_h9dcf22b6__2;
        CData/*5:0*/ tb_top__DOT__i_bar__DOT__i_bar_rsp_arbiter__DOT____Vlvbound_h9dcf22b6__1;
        CData/*4:0*/ tb_top__DOT__i_bar__DOT__i_bar_rsp_arbiter__DOT____Vlvbound_h0038da16__1;
        CData/*4:0*/ tb_top__DOT__i_bar__DOT__i_bar_rsp_arbiter__DOT____Vlvbound_h99f8a03b__1;
        CData/*5:0*/ tb_top__DOT__i_bar__DOT__i_bar_rsp_arbiter__DOT____Vlvbound_h9dcf22b6__0;
        CData/*4:0*/ tb_top__DOT__i_bar__DOT__i_bar_rsp_arbiter__DOT____Vlvbound_h0038da16__0;
        CData/*4:0*/ tb_top__DOT__i_bar__DOT__i_bar_rsp_arbiter__DOT____Vlvbound_h99f8a03b__0;
    };
    struct {
        CData/*0:0*/ tb_top__DOT__i_bar__DOT__i_bar_rsp_arbiter__DOT__clk;
        CData/*0:0*/ tb_top__DOT__i_bar__DOT__i_bar_rsp_arbiter__DOT__rst;
        CData/*6:0*/ tb_top__DOT__i_bar__DOT__i_bar_rsp_arbiter__DOT__in_valid;
        CData/*6:0*/ tb_top__DOT__i_bar__DOT__i_bar_rsp_arbiter__DOT__in_ready;
        CData/*0:0*/ tb_top__DOT__i_bar__DOT__i_bar_rsp_arbiter__DOT__out_valid;
        CData/*2:0*/ tb_top__DOT__i_bar__DOT__i_bar_rsp_arbiter__DOT__rr_ptr;
        CData/*2:0*/ tb_top__DOT__i_bar__DOT__i_bar_rsp_arbiter__DOT__selected;
        CData/*0:0*/ tb_top__DOT__i_bar__DOT__i_bar_rsp_arbiter__DOT__selected_valid;
        CData/*6:0*/ tb_top__DOT__i_bar__DOT__i_bar_rsp_arbiter__DOT__push;
        CData/*3:0*/ tb_top__DOT__i_bar__DOT__i_bar_rsp_arbiter__DOT__index;
        CData/*0:0*/ tb_top__DOT__i_bar__DOT__i_bar0__DOT__rst;
        CData/*0:0*/ tb_top__DOT__i_bar__DOT__i_bar0__DOT__clk;
        CData/*3:0*/ tb_top__DOT__i_bar__DOT__i_bar0__DOT__wr_be;
        CData/*0:0*/ tb_top__DOT__i_bar__DOT__i_bar0__DOT__wr_valid;
        CData/*0:0*/ tb_top__DOT__i_bar__DOT__i_bar0__DOT__rd_req_valid;
        CData/*0:0*/ tb_top__DOT__i_bar__DOT__i_bar0__DOT__rd_rsp_valid;
        CData/*0:0*/ tb_top__DOT__i_bar__DOT__i_bar0__DOT__rd_req_valid_d1;
        CData/*0:0*/ tb_top__DOT__i_bar__DOT__i_latency_emu__DOT__clk;
        CData/*0:0*/ tb_top__DOT__i_bar__DOT__i_latency_emu__DOT__rst;
        CData/*0:0*/ tb_top__DOT__i_bar__DOT__i_latency_emu__DOT__crst_falling;
        CData/*0:0*/ tb_top__DOT__i_bar__DOT__i_latency_emu__DOT__req_valid;
        CData/*0:0*/ tb_top__DOT__i_bar__DOT__i_latency_emu__DOT__req_ready;
        CData/*0:0*/ tb_top__DOT__i_bar__DOT__i_latency_emu__DOT__rsp_valid;
        CData/*0:0*/ tb_top__DOT__i_bar__DOT__i_latency_emu__DOT__rsp_ready;
        CData/*0:0*/ tb_top__DOT__i_bar__DOT__i_latency_emu__DOT__busy;
        CData/*0:0*/ tb_top__DOT__i_bar__DOT__i_latency_emu__DOT__wr_valid;
        CData/*0:0*/ tb_top__DOT__i_bar__DOT__i_latency_emu__DOT__wr_ack;
        CData/*0:0*/ tb_top__DOT__i_bar__DOT__i_latency_emu__DOT__request_pending;
        CData/*7:0*/ tb_top__DOT__i_bar__DOT__i_latency_emu__DOT__latency_counter;
        CData/*7:0*/ tb_top__DOT__i_bar__DOT__i_latency_emu__DOT__target_latency;
        CData/*7:0*/ tb_top__DOT__i_bar__DOT__i_latency_emu__DOT__prev_latency;
        CData/*0:0*/ tb_top__DOT__i_bar__DOT__i_latency_emu__DOT__prev_valid;
        CData/*3:0*/ tb_top__DOT__i_bar__DOT__i_latency_emu__DOT__idle_counter;
        CData/*0:0*/ tb_top__DOT__i_bar__DOT__i_latency_emu__DOT__timeout_expired;
        CData/*3:0*/ tb_top__DOT__i_bar__DOT__i_latency_emu__DOT__thermal_offset;
        CData/*2:0*/ tb_top__DOT__i_bar__DOT__i_latency_emu__DOT__addr_region;
        CData/*7:0*/ tb_top__DOT__i_bar__DOT__i_latency_emu__DOT__region_adjust;
        CData/*0:0*/ tb_top__DOT__i_bar__DOT__i_latency_emu__DOT__is_sequential;
        CData/*7:0*/ tb_top__DOT__i_bar__DOT__i_latency_emu__DOT__corr_weight;
        CData/*7:0*/ tb_top__DOT__i_bar__DOT__i_latency_emu__DOT__correlated_latency;
        CData/*3:0*/ tb_top__DOT__i_bar__DOT__i_latency_emu__DOT__cdf_bucket;
        CData/*7:0*/ tb_top__DOT__i_bar__DOT__i_latency_emu__DOT__latency_range;
        CData/*7:0*/ tb_top__DOT__i_bar__DOT__i_latency_emu__DOT__cdf_latency;
        CData/*7:0*/ tb_top__DOT__i_bar__DOT__i_latency_emu__DOT__base_jitter;
        CData/*7:0*/ tb_top__DOT__i_bar__DOT__i_latency_emu__DOT__thermal_adj;
        CData/*7:0*/ tb_top__DOT__i_bar__DOT__i_latency_emu__DOT__region_adj;
        CData/*7:0*/ tb_top__DOT__i_bar__DOT__i_latency_emu__DOT__jittered;
        CData/*7:0*/ tb_top__DOT__i_bar__DOT__i_latency_emu__DOT__computed_latency;
        CData/*7:0*/ tb_top__DOT__i_bar__DOT__i_latency_emu__DOT__wr_range;
        CData/*7:0*/ tb_top__DOT__i_bar__DOT__i_latency_emu__DOT__wr_latency;
        CData/*7:0*/ tb_top__DOT__i_bar__DOT__i_latency_emu__DOT__wr_counter;
        CData/*7:0*/ tb_top__DOT__i_bar__DOT__i_latency_emu__DOT__wr_target;
        CData/*0:0*/ tb_top__DOT__i_bar__DOT__i_latency_emu__DOT__wr_pending;
        CData/*0:0*/ tb_top__DOT__i_bar__DOT__i_bar1__DOT__rst;
        CData/*0:0*/ tb_top__DOT__i_bar__DOT__i_bar1__DOT__clk;
        CData/*3:0*/ tb_top__DOT__i_bar__DOT__i_bar1__DOT__wr_be;
        CData/*0:0*/ tb_top__DOT__i_bar__DOT__i_bar1__DOT__wr_valid;
        CData/*0:0*/ tb_top__DOT__i_bar__DOT__i_bar1__DOT__rd_req_valid;
        CData/*0:0*/ tb_top__DOT__i_bar__DOT__i_bar1__DOT__rd_rsp_valid;
        CData/*0:0*/ tb_top__DOT__i_bar__DOT__i_bar1__DOT__intr_req;
        CData/*0:0*/ tb_top__DOT__i_bar__DOT__i_bar2__DOT__rst;
        CData/*0:0*/ tb_top__DOT__i_bar__DOT__i_bar2__DOT__clk;
        CData/*3:0*/ tb_top__DOT__i_bar__DOT__i_bar2__DOT__wr_be;
        CData/*0:0*/ tb_top__DOT__i_bar__DOT__i_bar2__DOT__wr_valid;
    };
    struct {
        CData/*0:0*/ tb_top__DOT__i_bar__DOT__i_bar2__DOT__rd_req_valid;
        CData/*0:0*/ tb_top__DOT__i_bar__DOT__i_bar2__DOT__rd_rsp_valid;
        CData/*0:0*/ tb_top__DOT__i_bar__DOT__i_bar2__DOT__intr_req;
        CData/*0:0*/ tb_top__DOT__i_bar__DOT__i_bar3__DOT__rst;
        CData/*0:0*/ tb_top__DOT__i_bar__DOT__i_bar3__DOT__clk;
        CData/*3:0*/ tb_top__DOT__i_bar__DOT__i_bar3__DOT__wr_be;
        CData/*0:0*/ tb_top__DOT__i_bar__DOT__i_bar3__DOT__wr_valid;
        CData/*0:0*/ tb_top__DOT__i_bar__DOT__i_bar3__DOT__rd_req_valid;
        CData/*0:0*/ tb_top__DOT__i_bar__DOT__i_bar3__DOT__rd_rsp_valid;
        CData/*0:0*/ tb_top__DOT__i_bar__DOT__i_bar3__DOT__intr_req;
        CData/*0:0*/ tb_top__DOT__i_bar__DOT__i_bar4__DOT__rst;
        CData/*0:0*/ tb_top__DOT__i_bar__DOT__i_bar4__DOT__clk;
        CData/*3:0*/ tb_top__DOT__i_bar__DOT__i_bar4__DOT__wr_be;
        CData/*0:0*/ tb_top__DOT__i_bar__DOT__i_bar4__DOT__wr_valid;
        CData/*0:0*/ tb_top__DOT__i_bar__DOT__i_bar4__DOT__rd_req_valid;
        CData/*0:0*/ tb_top__DOT__i_bar__DOT__i_bar4__DOT__rd_rsp_valid;
        CData/*0:0*/ tb_top__DOT__i_bar__DOT__i_bar4__DOT__intr_req;
        CData/*0:0*/ tb_top__DOT__i_bar__DOT__i_bar5__DOT__rst;
        CData/*0:0*/ tb_top__DOT__i_bar__DOT__i_bar5__DOT__clk;
        CData/*3:0*/ tb_top__DOT__i_bar__DOT__i_bar5__DOT__wr_be;
        CData/*0:0*/ tb_top__DOT__i_bar__DOT__i_bar5__DOT__wr_valid;
        CData/*0:0*/ tb_top__DOT__i_bar__DOT__i_bar5__DOT__rd_req_valid;
        CData/*0:0*/ tb_top__DOT__i_bar__DOT__i_bar5__DOT__rd_rsp_valid;
        CData/*0:0*/ tb_top__DOT__i_bar__DOT__i_bar5__DOT__intr_req;
        CData/*3:0*/ __Vfunc_tb_top__DOT__i_bar__DOT__i_tlp_normalizer__DOT__valid_first_edge__2__value;
        CData/*3:0*/ __Vfunc_tb_top__DOT__i_bar__DOT__i_tlp_normalizer__DOT__valid_last_edge__3__value;
        CData/*3:0*/ __Vfunc_tb_top__DOT__i_bar__DOT__i_tlp_normalizer__DOT__popcount4__4__value;
        CData/*3:0*/ __Vfunc_tb_top__DOT__i_bar__DOT__i_tlp_normalizer__DOT__popcount4__5__value;
        CData/*3:0*/ __Vfunc_tb_top__DOT__i_bar__DOT__i_tlp_normalizer__DOT__popcount4__6__value;
        CData/*0:0*/ __Vtrigprevexpr___TOP__tb_top__DOT__i_bar__DOT__cpl_select_ur__0;
        CData/*0:0*/ __VstlDidInit;
        CData/*0:0*/ __VstlFirstIteration;
        CData/*0:0*/ __VstlPhaseResult;
        CData/*0:0*/ __VicoDidInit;
        CData/*0:0*/ __VicoFirstIteration;
        CData/*0:0*/ __VicoPhaseResult;
        CData/*0:0*/ __Vtrigprevexpr___TOP__tb_top__DOT__i_bar__DOT__cpl_select_ur__1;
        CData/*0:0*/ __Vtrigprevexpr___TOP__tb_top__DOT__i_bar__DOT__clk__0;
        CData/*0:0*/ __Vtrigprevexpr___TOP__tb_top__DOT__i_bar__DOT__i_lifecycle_service__DOT__clk__0;
        CData/*0:0*/ __Vtrigprevexpr___TOP__tb_top__DOT__i_bar__DOT__i_pcileech_tlps128_bar_rdengine__DOT__clk__0;
        CData/*0:0*/ __Vtrigprevexpr___TOP__tb_top__DOT__i_bar__DOT__i_pcileech_tlps128_bar_rdengine__DOT__i_fifo_134_134_clk1_bar_rdrsp__DOT__clk__0;
        CData/*0:0*/ __Vtrigprevexpr___TOP__tb_top__DOT__i_bar__DOT__i_tlp_ur_completer__DOT__clk__0;
        CData/*0:0*/ __Vtrigprevexpr___TOP__tb_top__DOT__i_bar__DOT__i_pcileech_tlps128_bar_wrengine__DOT__clk__0;
        CData/*0:0*/ __Vtrigprevexpr___TOP__tb_top__DOT__i_bar__DOT__i_bar_rsp_arbiter__DOT__clk__0;
        CData/*0:0*/ __Vtrigprevexpr___TOP__tb_top__DOT__i_bar__DOT__i_bar0__DOT__clk__0;
        CData/*0:0*/ __Vtrigprevexpr___TOP__tb_top__DOT__i_bar__DOT__i_latency_emu__DOT__clk__0;
        CData/*0:0*/ __VactPhaseResult;
        CData/*0:0*/ __VinactPhaseResult;
        CData/*0:0*/ __VnbaPhaseResult;
        SData/*15:0*/ tb_top__DOT__cfg_command;
        SData/*15:0*/ tb_top__DOT__pcie_id;
        SData/*8:0*/ tb_top__DOT__tlps_in_tuser;
        SData/*8:0*/ tb_top__DOT__tlps_out_tuser;
        SData/*15:0*/ tb_top__DOT__i_bar__DOT__pcie_id;
        SData/*15:0*/ tb_top__DOT__i_bar__DOT__cfg_command;
        SData/*10:0*/ tb_top__DOT__i_bar__DOT__norm_length_dw;
        SData/*15:0*/ tb_top__DOT__i_bar__DOT__norm_requester_id;
        SData/*12:0*/ tb_top__DOT__i_bar__DOT__norm_enabled_byte_count;
        SData/*12:0*/ tb_top__DOT__i_bar__DOT__norm_first_completion_byte_count;
        SData/*10:0*/ tb_top__DOT__i_bar__DOT__norm_first_completion_dw;
        SData/*8:0*/ tb_top__DOT__i_bar__DOT__ur_request_count;
        SData/*12:0*/ tb_top__DOT__i_bar__DOT__i_tlp_normalizer__DOT____VlemCond_6;
        SData/*8:0*/ tb_top__DOT__i_bar__DOT__i_tlp_normalizer__DOT__tlp_user;
        SData/*10:0*/ tb_top__DOT__i_bar__DOT__i_tlp_normalizer__DOT__length_dw;
    };
    struct {
        SData/*15:0*/ tb_top__DOT__i_bar__DOT__i_tlp_normalizer__DOT__requester_id;
        SData/*12:0*/ tb_top__DOT__i_bar__DOT__i_tlp_normalizer__DOT__enabled_byte_count;
        SData/*12:0*/ tb_top__DOT__i_bar__DOT__i_tlp_normalizer__DOT__first_completion_byte_count;
        SData/*10:0*/ tb_top__DOT__i_bar__DOT__i_tlp_normalizer__DOT__first_completion_dw;
        SData/*12:0*/ tb_top__DOT__i_bar__DOT__i_tlp_normalizer__DOT__rcb_bytes_left;
        SData/*10:0*/ tb_top__DOT__i_bar__DOT__i_tlp_normalizer__DOT__rcb_dw_left;
        SData/*10:0*/ tb_top__DOT__i_bar__DOT__i_tlp_normalizer__DOT__mps_dw;
        SData/*12:0*/ tb_top__DOT__i_bar__DOT__i_pcileech_tlps128_bar_rdengine__DOT____VlemCall_0__completed_enabled_bytes;
        SData/*15:0*/ tb_top__DOT__i_bar__DOT__i_pcileech_tlps128_bar_rdengine__DOT__pcie_id;
        SData/*10:0*/ tb_top__DOT__i_bar__DOT__i_pcileech_tlps128_bar_rdengine__DOT__norm_length_dw;
        SData/*15:0*/ tb_top__DOT__i_bar__DOT__i_pcileech_tlps128_bar_rdengine__DOT__norm_requester_id;
        SData/*12:0*/ tb_top__DOT__i_bar__DOT__i_pcileech_tlps128_bar_rdengine__DOT__norm_enabled_byte_count;
        SData/*12:0*/ tb_top__DOT__i_bar__DOT__i_pcileech_tlps128_bar_rdengine__DOT__norm_first_completion_byte_count;
        SData/*10:0*/ tb_top__DOT__i_bar__DOT__i_pcileech_tlps128_bar_rdengine__DOT__norm_first_completion_dw;
        SData/*8:0*/ tb_top__DOT__i_bar__DOT__i_pcileech_tlps128_bar_rdengine__DOT__req_count;
        SData/*10:0*/ tb_top__DOT__i_bar__DOT__i_pcileech_tlps128_bar_rdengine__DOT__request_length_dw;
        SData/*10:0*/ tb_top__DOT__i_bar__DOT__i_pcileech_tlps128_bar_rdengine__DOT__remaining_dw;
        SData/*10:0*/ tb_top__DOT__i_bar__DOT__i_pcileech_tlps128_bar_rdengine__DOT__packet_length_dw;
        SData/*10:0*/ tb_top__DOT__i_bar__DOT__i_pcileech_tlps128_bar_rdengine__DOT__packet_remaining_dw;
        SData/*12:0*/ tb_top__DOT__i_bar__DOT__i_pcileech_tlps128_bar_rdengine__DOT__remaining_byte_count;
        SData/*15:0*/ tb_top__DOT__i_bar__DOT__i_pcileech_tlps128_bar_rdengine__DOT__request_id;
        SData/*10:0*/ tb_top__DOT__i_bar__DOT__i_pcileech_tlps128_bar_rdengine__DOT__rd_rsp_dwlen;
        SData/*11:0*/ tb_top__DOT__i_bar__DOT__i_pcileech_tlps128_bar_rdengine__DOT__rd_rsp_byte_count;
        SData/*15:0*/ tb_top__DOT__i_bar__DOT__i_pcileech_tlps128_bar_rdengine__DOT__rd_rsp_requester;
        SData/*10:0*/ tb_top__DOT__i_bar__DOT__i_pcileech_tlps128_bar_rdengine__DOT__i_fifo_134_134_clk1_bar_rdrsp__DOT__rd_data_count;
        SData/*10:0*/ tb_top__DOT__i_bar__DOT__i_pcileech_tlps128_bar_rdengine__DOT__i_fifo_134_134_clk1_bar_rdrsp__DOT__wr_data_count;
        SData/*10:0*/ tb_top__DOT__i_bar__DOT__i_pcileech_tlps128_bar_rdengine__DOT__i_fifo_134_134_clk1_bar_rdrsp__DOT__wr_ptr;
        SData/*10:0*/ tb_top__DOT__i_bar__DOT__i_pcileech_tlps128_bar_rdengine__DOT__i_fifo_134_134_clk1_bar_rdrsp__DOT__rd_ptr;
        SData/*10:0*/ tb_top__DOT__i_bar__DOT__i_pcileech_tlps128_bar_rdengine__DOT__i_fifo_134_134_clk1_bar_rdrsp__DOT__count;
        SData/*15:0*/ tb_top__DOT__i_bar__DOT__i_tlp_ur_completer__DOT__pcie_id;
        SData/*15:0*/ tb_top__DOT__i_bar__DOT__i_tlp_ur_completer__DOT__requester_id;
        SData/*8:0*/ tb_top__DOT__i_bar__DOT__i_tlp_ur_completer__DOT__request_count;
        SData/*8:0*/ tb_top__DOT__i_bar__DOT__i_pcileech_tlps128_bar_wrengine__DOT__f_tuser;
        SData/*9:0*/ tb_top__DOT__i_bar__DOT__i_bar0__DOT__wr_word;
        SData/*9:0*/ tb_top__DOT__i_bar__DOT__i_bar0__DOT__rd_word;
        SData/*15:0*/ tb_top__DOT__i_bar__DOT__i_latency_emu__DOT__thermal_counter;
        VlWide<4>/*127:0*/ tb_top__DOT__tlps_in_tdata;
        VlWide<4>/*127:0*/ tb_top__DOT__tlps_out_tdata;
        IData/*31:0*/ tb_top__DOT__i_bar__DOT__lifecycle_generation;
        IData/*31:0*/ tb_top__DOT__i_bar__DOT__wr_addr;
        IData/*31:0*/ tb_top__DOT__i_bar__DOT__wr_data;
        VlWide<3>/*87:0*/ tb_top__DOT__i_bar__DOT__rd_req_ctx;
        IData/*31:0*/ tb_top__DOT__i_bar__DOT__rd_req_addr;
        VlWide<3>/*87:0*/ tb_top__DOT__i_bar__DOT__rd_rsp_ctx;
        IData/*31:0*/ tb_top__DOT__i_bar__DOT__rd_rsp_data;
        IData/*31:0*/ tb_top__DOT__i_bar__DOT__wr_addr_bar0;
        IData/*31:0*/ tb_top__DOT__i_bar__DOT__rd_req_addr_bar0;
        VlWide<3>/*87:0*/ tb_top__DOT__i_bar__DOT__bar0_raw_ctx;
        IData/*31:0*/ tb_top__DOT__i_bar__DOT__bar0_raw_data;
        VlWide<3>/*87:0*/ tb_top__DOT__i_bar__DOT__bar0_emu_ctx;
        IData/*31:0*/ tb_top__DOT__i_bar__DOT__bar0_emu_data;
        VlWide<3>/*87:0*/ tb_top__DOT__i_bar__DOT__bar0_buf_ctx_w;
        IData/*31:0*/ tb_top__DOT__i_bar__DOT__bar0_buf_data_w;
        IData/*31:0*/ tb_top__DOT__i_bar__DOT__bar0_buf_addr_w;
        IData/*31:0*/ tb_top__DOT__i_bar__DOT__bar0_req_addr_from_ctx;
        VlWide<3>/*87:0*/ tb_top__DOT__i_bar__DOT__bar0_spill_ctx;
        IData/*31:0*/ tb_top__DOT__i_bar__DOT__bar0_spill_data;
        VlWide<3>/*87:0*/ tb_top__DOT__i_bar__DOT__bar0_base_ctx;
        IData/*31:0*/ tb_top__DOT__i_bar__DOT__bar0_base_data;
        IData/*31:0*/ tb_top__DOT__i_bar__DOT__i_lifecycle_service__DOT__generation;
        VlWide<4>/*127:0*/ tb_top__DOT__i_bar__DOT__i_tlp_normalizer__DOT__tlp_data;
        VlWide<3>/*87:0*/ tb_top__DOT__i_bar__DOT__i_pcileech_tlps128_bar_rdengine__DOT__rd_req_ctx;
        IData/*31:0*/ tb_top__DOT__i_bar__DOT__i_pcileech_tlps128_bar_rdengine__DOT__rd_req_addr;
        VlWide<3>/*87:0*/ tb_top__DOT__i_bar__DOT__i_pcileech_tlps128_bar_rdengine__DOT__rd_rsp_ctx;
    };
    struct {
        IData/*31:0*/ tb_top__DOT__i_bar__DOT__i_pcileech_tlps128_bar_rdengine__DOT__rd_rsp_data;
        IData/*31:0*/ tb_top__DOT__i_bar__DOT__i_pcileech_tlps128_bar_rdengine__DOT__context_address;
        IData/*31:0*/ tb_top__DOT__i_bar__DOT__i_pcileech_tlps128_bar_rdengine__DOT__rd_rsp_data_swapped;
        VlWide<4>/*127:0*/ tb_top__DOT__i_bar__DOT__i_pcileech_tlps128_bar_rdengine__DOT__tdata;
        VlWide<5>/*133:0*/ tb_top__DOT__i_bar__DOT__i_pcileech_tlps128_bar_rdengine__DOT__i_fifo_134_134_clk1_bar_rdrsp__DOT__din;
        VlWide<5>/*133:0*/ tb_top__DOT__i_bar__DOT__i_pcileech_tlps128_bar_rdengine__DOT__i_fifo_134_134_clk1_bar_rdrsp__DOT__dout;
        VlWide<4>/*127:0*/ tb_top__DOT__i_bar__DOT__i_tlp_ur_completer__DOT__completion_data;
        IData/*31:0*/ tb_top__DOT__i_bar__DOT__i_pcileech_tlps128_bar_wrengine__DOT__wr_addr;
        IData/*31:0*/ tb_top__DOT__i_bar__DOT__i_pcileech_tlps128_bar_wrengine__DOT__wr_data;
        VlWide<4>/*127:0*/ tb_top__DOT__i_bar__DOT__i_pcileech_tlps128_bar_wrengine__DOT__f_tdata;
        VlWide<4>/*127:0*/ tb_top__DOT__i_bar__DOT__i_pcileech_tlps128_bar_wrengine__DOT__tdata;
        IData/*31:0*/ tb_top__DOT__i_bar__DOT__i_pcileech_tlps128_bar_wrengine__DOT__addr;
        VlWide<5>/*140:0*/ tb_top__DOT__i_bar__DOT__i_pcileech_tlps128_bar_wrengine__DOT__i_fifo_141_141_clk1_bar_wr__DOT__din;
        VlWide<5>/*140:0*/ tb_top__DOT__i_bar__DOT__i_pcileech_tlps128_bar_wrengine__DOT__i_fifo_141_141_clk1_bar_wr__DOT__dout;
        IData/*31:0*/ tb_top__DOT__i_bar__DOT__i_bar_rsp_arbiter__DOT____Vlvbound_hd1ae10b8__0;
        VlWide<3>/*87:0*/ tb_top__DOT__i_bar__DOT__i_bar_rsp_arbiter__DOT____Vlvbound_h511400fb__0;
        VlWide<3>/*87:0*/ tb_top__DOT__i_bar__DOT__i_bar_rsp_arbiter__DOT__out_ctx;
        IData/*31:0*/ tb_top__DOT__i_bar__DOT__i_bar_rsp_arbiter__DOT__out_data;
        IData/*31:0*/ tb_top__DOT__i_bar__DOT__i_bar_rsp_arbiter__DOT__scan;
        IData/*31:0*/ tb_top__DOT__i_bar__DOT__i_bar_rsp_arbiter__DOT__k;
        IData/*31:0*/ tb_top__DOT__i_bar__DOT__i_bar0__DOT__wr_addr;
        IData/*31:0*/ tb_top__DOT__i_bar__DOT__i_bar0__DOT__wr_data;
        VlWide<3>/*87:0*/ tb_top__DOT__i_bar__DOT__i_bar0__DOT__rd_req_ctx;
        IData/*31:0*/ tb_top__DOT__i_bar__DOT__i_bar0__DOT__rd_req_addr;
        VlWide<3>/*87:0*/ tb_top__DOT__i_bar__DOT__i_bar0__DOT__rd_rsp_ctx;
        IData/*31:0*/ tb_top__DOT__i_bar__DOT__i_bar0__DOT__rd_rsp_data;
        VlWide<3>/*87:0*/ tb_top__DOT__i_bar__DOT__i_bar0__DOT__rd_req_ctx_d1;
        IData/*31:0*/ tb_top__DOT__i_bar__DOT__i_bar0__DOT__rd_data_d1;
        IData/*31:0*/ tb_top__DOT__i_bar__DOT__i_bar0__DOT__i;
        VlWide<3>/*87:0*/ tb_top__DOT__i_bar__DOT__i_latency_emu__DOT__req_ctx;
        IData/*31:0*/ tb_top__DOT__i_bar__DOT__i_latency_emu__DOT__req_data;
        IData/*31:0*/ tb_top__DOT__i_bar__DOT__i_latency_emu__DOT__req_addr;
        VlWide<3>/*87:0*/ tb_top__DOT__i_bar__DOT__i_latency_emu__DOT__rsp_ctx;
        IData/*31:0*/ tb_top__DOT__i_bar__DOT__i_latency_emu__DOT__rsp_data;
        IData/*31:0*/ tb_top__DOT__i_bar__DOT__i_latency_emu__DOT__wr_addr;
        VlWide<3>/*87:0*/ tb_top__DOT__i_bar__DOT__i_latency_emu__DOT__stored_ctx;
        IData/*31:0*/ tb_top__DOT__i_bar__DOT__i_latency_emu__DOT__stored_data;
        IData/*31:0*/ tb_top__DOT__i_bar__DOT__i_latency_emu__DOT__prev_addr;
        IData/*18:0*/ tb_top__DOT__i_bar__DOT__i_latency_emu__DOT__timeout_counter;
        IData/*31:0*/ tb_top__DOT__i_bar__DOT__i_latency_emu__DOT__prng_s0;
        IData/*31:0*/ tb_top__DOT__i_bar__DOT__i_latency_emu__DOT__prng_s1;
        IData/*31:0*/ tb_top__DOT__i_bar__DOT__i_latency_emu__DOT__prng_s2;
        IData/*31:0*/ tb_top__DOT__i_bar__DOT__i_latency_emu__DOT__prng_s3;
        IData/*31:0*/ tb_top__DOT__i_bar__DOT__i_latency_emu__DOT__prng_out;
        IData/*31:0*/ tb_top__DOT__i_bar__DOT__i_latency_emu__DOT__prng_next_s0;
        IData/*31:0*/ tb_top__DOT__i_bar__DOT__i_latency_emu__DOT__prng_next_s3;
        IData/*31:0*/ tb_top__DOT__i_bar__DOT__i_bar1__DOT__wr_addr;
        IData/*31:0*/ tb_top__DOT__i_bar__DOT__i_bar1__DOT__wr_data;
        VlWide<3>/*87:0*/ tb_top__DOT__i_bar__DOT__i_bar1__DOT__rd_req_ctx;
        IData/*31:0*/ tb_top__DOT__i_bar__DOT__i_bar1__DOT__rd_req_addr;
        VlWide<3>/*87:0*/ tb_top__DOT__i_bar__DOT__i_bar1__DOT__rd_rsp_ctx;
        IData/*31:0*/ tb_top__DOT__i_bar__DOT__i_bar1__DOT__rd_rsp_data;
        IData/*31:0*/ tb_top__DOT__i_bar__DOT__i_bar2__DOT__wr_addr;
        IData/*31:0*/ tb_top__DOT__i_bar__DOT__i_bar2__DOT__wr_data;
        VlWide<3>/*87:0*/ tb_top__DOT__i_bar__DOT__i_bar2__DOT__rd_req_ctx;
        IData/*31:0*/ tb_top__DOT__i_bar__DOT__i_bar2__DOT__rd_req_addr;
        VlWide<3>/*87:0*/ tb_top__DOT__i_bar__DOT__i_bar2__DOT__rd_rsp_ctx;
        IData/*31:0*/ tb_top__DOT__i_bar__DOT__i_bar2__DOT__rd_rsp_data;
        IData/*31:0*/ tb_top__DOT__i_bar__DOT__i_bar3__DOT__wr_addr;
        IData/*31:0*/ tb_top__DOT__i_bar__DOT__i_bar3__DOT__wr_data;
        VlWide<3>/*87:0*/ tb_top__DOT__i_bar__DOT__i_bar3__DOT__rd_req_ctx;
        IData/*31:0*/ tb_top__DOT__i_bar__DOT__i_bar3__DOT__rd_req_addr;
        VlWide<3>/*87:0*/ tb_top__DOT__i_bar__DOT__i_bar3__DOT__rd_rsp_ctx;
        IData/*31:0*/ tb_top__DOT__i_bar__DOT__i_bar3__DOT__rd_rsp_data;
    };
    struct {
        IData/*31:0*/ tb_top__DOT__i_bar__DOT__i_bar4__DOT__wr_addr;
        IData/*31:0*/ tb_top__DOT__i_bar__DOT__i_bar4__DOT__wr_data;
        VlWide<3>/*87:0*/ tb_top__DOT__i_bar__DOT__i_bar4__DOT__rd_req_ctx;
        IData/*31:0*/ tb_top__DOT__i_bar__DOT__i_bar4__DOT__rd_req_addr;
        VlWide<3>/*87:0*/ tb_top__DOT__i_bar__DOT__i_bar4__DOT__rd_rsp_ctx;
        IData/*31:0*/ tb_top__DOT__i_bar__DOT__i_bar4__DOT__rd_rsp_data;
        IData/*31:0*/ tb_top__DOT__i_bar__DOT__i_bar5__DOT__wr_addr;
        IData/*31:0*/ tb_top__DOT__i_bar__DOT__i_bar5__DOT__wr_data;
        VlWide<3>/*87:0*/ tb_top__DOT__i_bar__DOT__i_bar5__DOT__rd_req_ctx;
        IData/*31:0*/ tb_top__DOT__i_bar__DOT__i_bar5__DOT__rd_req_addr;
        VlWide<3>/*87:0*/ tb_top__DOT__i_bar__DOT__i_bar5__DOT__rd_rsp_ctx;
        IData/*31:0*/ tb_top__DOT__i_bar__DOT__i_bar5__DOT__rd_rsp_data;
        IData/*31:0*/ __VactIterCount;
        IData/*31:0*/ __VinactIterCount;
        IData/*31:0*/ __Vi;
        QData/*63:0*/ tb_top__DOT__i_bar__DOT__norm_address;
        QData/*63:0*/ tb_top__DOT__i_bar__DOT__i_tlp_normalizer__DOT__address;
        QData/*63:0*/ tb_top__DOT__i_bar__DOT__i_pcileech_tlps128_bar_rdengine__DOT__norm_address;
        QData/*63:0*/ tb_top__DOT__i_bar__DOT__i_pcileech_tlps128_bar_rdengine__DOT__current_addr;
        VlUnpacked<IData/*29:0*/, 256> tb_top__DOT__i_bar__DOT__ur_request_fifo;
        VlUnpacked<VlWide<3>/*87:0*/, 16> tb_top__DOT__i_bar__DOT__bar0_buf_ctx;
        VlUnpacked<IData/*31:0*/, 16> tb_top__DOT__i_bar__DOT__bar0_buf_data;
        VlUnpacked<IData/*31:0*/, 16> tb_top__DOT__i_bar__DOT__bar0_buf_addr;
        VlUnpacked<VlWide<3>/*87:0*/, 7> tb_top__DOT__i_bar__DOT__bar_base_ctx;
        VlUnpacked<IData/*31:0*/, 7> tb_top__DOT__i_bar__DOT__bar_base_data;
        VlUnpacked<VlWide<3>/*87:0*/, 7> tb_top__DOT__i_bar__DOT__bar_rsp_ctx;
        VlUnpacked<IData/*31:0*/, 7> tb_top__DOT__i_bar__DOT__bar_rsp_data;
        VlUnpacked<IData/*31:0*/, 7> tb_top__DOT__i_bar__DOT____Vcellinp__i_bar_rsp_arbiter__in_data;
        VlUnpacked<VlWide<3>/*87:0*/, 7> tb_top__DOT__i_bar__DOT____Vcellinp__i_bar_rsp_arbiter__in_ctx;
        VlUnpacked<QData/*63:0*/, 256> tb_top__DOT__i_bar__DOT__i_pcileech_tlps128_bar_rdengine__DOT__req_addr_fifo;
        VlUnpacked<SData/*10:0*/, 256> tb_top__DOT__i_bar__DOT__i_pcileech_tlps128_bar_rdengine__DOT__req_len_fifo;
        VlUnpacked<CData/*3:0*/, 256> tb_top__DOT__i_bar__DOT__i_pcileech_tlps128_bar_rdengine__DOT__req_fbe_fifo;
        VlUnpacked<CData/*3:0*/, 256> tb_top__DOT__i_bar__DOT__i_pcileech_tlps128_bar_rdengine__DOT__req_lbe_fifo;
        VlUnpacked<SData/*15:0*/, 256> tb_top__DOT__i_bar__DOT__i_pcileech_tlps128_bar_rdengine__DOT__req_id_fifo;
        VlUnpacked<CData/*7:0*/, 256> tb_top__DOT__i_bar__DOT__i_pcileech_tlps128_bar_rdengine__DOT__req_tag_fifo;
        VlUnpacked<CData/*2:0*/, 256> tb_top__DOT__i_bar__DOT__i_pcileech_tlps128_bar_rdengine__DOT__req_tc_fifo;
        VlUnpacked<CData/*2:0*/, 256> tb_top__DOT__i_bar__DOT__i_pcileech_tlps128_bar_rdengine__DOT__req_attr_fifo;
        VlUnpacked<CData/*0:0*/, 256> tb_top__DOT__i_bar__DOT__i_pcileech_tlps128_bar_rdengine__DOT__req_4dw_fifo;
        VlUnpacked<CData/*6:0*/, 256> tb_top__DOT__i_bar__DOT__i_pcileech_tlps128_bar_rdengine__DOT__req_bar_fifo;
        VlUnpacked<SData/*12:0*/, 256> tb_top__DOT__i_bar__DOT__i_pcileech_tlps128_bar_rdengine__DOT__req_bc_fifo;
        VlUnpacked<SData/*10:0*/, 256> tb_top__DOT__i_bar__DOT__i_pcileech_tlps128_bar_rdengine__DOT__req_cpl_fifo;
        VlUnpacked<VlWide<5>/*133:0*/, 1024> tb_top__DOT__i_bar__DOT__i_pcileech_tlps128_bar_rdengine__DOT__i_fifo_134_134_clk1_bar_rdrsp__DOT__mem;
        VlUnpacked<SData/*15:0*/, 256> tb_top__DOT__i_bar__DOT__i_tlp_ur_completer__DOT__requester_fifo;
        VlUnpacked<CData/*7:0*/, 256> tb_top__DOT__i_bar__DOT__i_tlp_ur_completer__DOT__tag_fifo;
        VlUnpacked<CData/*2:0*/, 256> tb_top__DOT__i_bar__DOT__i_tlp_ur_completer__DOT__tc_fifo;
        VlUnpacked<CData/*2:0*/, 256> tb_top__DOT__i_bar__DOT__i_tlp_ur_completer__DOT__attr_fifo;
        VlUnpacked<VlWide<3>/*87:0*/, 7> tb_top__DOT__i_bar__DOT__i_bar_rsp_arbiter__DOT__in_ctx;
        VlUnpacked<IData/*31:0*/, 7> tb_top__DOT__i_bar__DOT__i_bar_rsp_arbiter__DOT__in_data;
        VlUnpacked<VlUnpacked<VlWide<3>/*87:0*/, 32>, 7> tb_top__DOT__i_bar__DOT__i_bar_rsp_arbiter__DOT__ctx_mem;
        VlUnpacked<VlUnpacked<IData/*31:0*/, 32>, 7> tb_top__DOT__i_bar__DOT__i_bar_rsp_arbiter__DOT__data_mem;
        VlUnpacked<CData/*4:0*/, 7> tb_top__DOT__i_bar__DOT__i_bar_rsp_arbiter__DOT__wr_ptr;
        VlUnpacked<CData/*4:0*/, 7> tb_top__DOT__i_bar__DOT__i_bar_rsp_arbiter__DOT__rd_ptr;
        VlUnpacked<CData/*5:0*/, 7> tb_top__DOT__i_bar__DOT__i_bar_rsp_arbiter__DOT__count;
        VlUnpacked<IData/*31:0*/, 1024> tb_top__DOT__i_bar__DOT__i_bar0__DOT__bar_mem;
        VlUnpacked<CData/*7:0*/, 16> tb_top__DOT__i_bar__DOT__i_latency_emu__DOT__cdf_table;
        VlUnpacked<QData/*63:0*/, 2> __VstlTriggered;
        VlUnpacked<QData/*63:0*/, 2> __VicoTriggered;
        VlUnpacked<QData/*63:0*/, 1> __VactTriggered;
        VlUnpacked<QData/*63:0*/, 1> __VactTriggeredAcc;
        VlUnpacked<QData/*63:0*/, 1> __VnbaTriggered;
    };
    VlNBACommitQueue<VlUnpacked<CData/*4:0*/, 7>, false, CData/*4:0*/, 1> __VdlyCommitQueuetb_top__DOT__i_bar__DOT__i_bar_rsp_arbiter__DOT__wr_ptr;
    VlNBACommitQueue<VlUnpacked<CData/*4:0*/, 7>, false, CData/*4:0*/, 1> __VdlyCommitQueuetb_top__DOT__i_bar__DOT__i_bar_rsp_arbiter__DOT__rd_ptr;
    VlNBACommitQueue<VlUnpacked<CData/*5:0*/, 7>, false, CData/*5:0*/, 1> __VdlyCommitQueuetb_top__DOT__i_bar__DOT__i_bar_rsp_arbiter__DOT__count;
    VlNBACommitQueue<VlUnpacked<VlUnpacked<VlWide<3>/*87:0*/, 32>, 7>, false, VlWide<3>/*87:0*/, 2> __VdlyCommitQueuetb_top__DOT__i_bar__DOT__i_bar_rsp_arbiter__DOT__ctx_mem;
    VlNBACommitQueue<VlUnpacked<VlUnpacked<IData/*31:0*/, 32>, 7>, false, IData/*31:0*/, 2> __VdlyCommitQueuetb_top__DOT__i_bar__DOT__i_bar_rsp_arbiter__DOT__data_mem;
    VlDelayScheduler __VdlySched;

    // INTERNAL VARIABLES
    Vtop__Syms* vlSymsp;
    const char* vlNamep;

    // PARAMETERS
    static constexpr CData/*0:0*/ tb_top__DOT__i_bar__DOT__NVME_IO_QUEUES_ENABLED = 1U;
    static constexpr CData/*0:0*/ tb_top__DOT__i_bar__DOT__NVME_IO_DATA_STUBBED = 0U;
    static constexpr CData/*0:0*/ tb_top__DOT__i_bar__DOT__NVME_IO_READS_ZEROED = 0U;
    static constexpr CData/*0:0*/ tb_top__DOT__i_bar__DOT__NVME_IO_PRP_ONLY = 0U;
    static constexpr CData/*0:0*/ tb_top__DOT__i_bar__DOT__NVME_TIMING_ENABLED = 0U;
    static constexpr CData/*2:0*/ tb_top__DOT__i_bar__DOT__i_tlp_normalizer__DOT__KIND_UNKNOWN = 0U;
    static constexpr CData/*2:0*/ tb_top__DOT__i_bar__DOT__i_tlp_normalizer__DOT__KIND_MRD = 1U;
    static constexpr CData/*2:0*/ tb_top__DOT__i_bar__DOT__i_tlp_normalizer__DOT__KIND_MWR = 2U;
    static constexpr CData/*2:0*/ tb_top__DOT__i_bar__DOT__i_tlp_normalizer__DOT__KIND_IORD = 3U;
    static constexpr CData/*2:0*/ tb_top__DOT__i_bar__DOT__i_tlp_normalizer__DOT__KIND_IOWR = 4U;
    static constexpr CData/*2:0*/ tb_top__DOT__i_bar__DOT__i_tlp_normalizer__DOT__KIND_ATOMIC = 5U;
    static constexpr CData/*2:0*/ tb_top__DOT__i_bar__DOT__i_tlp_normalizer__DOT__KIND_MRDLK = 6U;
    static constexpr CData/*2:0*/ tb_top__DOT__i_bar__DOT__i_tlp_normalizer__DOT__KIND_CONFIG = 7U;
    static constexpr CData/*0:0*/ tb_top__DOT__i_bar__DOT__i_pcileech_tlps128_bar_rdengine__DOT__ST_IDLE = 0U;
    static constexpr CData/*0:0*/ tb_top__DOT__i_bar__DOT__i_pcileech_tlps128_bar_rdengine__DOT__ST_ISSUE = 1U;
    static constexpr IData/*31:0*/ tb_top__DOT__i_bar__DOT__NVME_BRAM_DISK_WORDS = 0x00008000U;
    static constexpr IData/*31:0*/ tb_top__DOT__i_bar__DOT__NVME_TIMING_CLOCK_HZ = 0x07735940U;
    static constexpr IData/*31:0*/ tb_top__DOT__i_bar__DOT__i_tlp_normalizer__DOT__READ_COMPLETION_BOUNDARY = 0x00000040U;
    static constexpr IData/*31:0*/ tb_top__DOT__i_bar__DOT__i_tlp_normalizer__DOT__MAX_PAYLOAD_BYTES = 0x00000080U;
    static constexpr IData/*31:0*/ tb_top__DOT__i_bar__DOT__i_pcileech_tlps128_bar_rdengine__DOT__READ_COMPLETION_BOUNDARY = 0x00000040U;
    static constexpr IData/*31:0*/ tb_top__DOT__i_bar__DOT__i_pcileech_tlps128_bar_rdengine__DOT__MAX_PAYLOAD_BYTES = 0x00000080U;
    static constexpr IData/*31:0*/ tb_top__DOT__i_bar__DOT__i_pcileech_tlps128_bar_rdengine__DOT__REQUEST_FIFO_DEPTH = 0x00000100U;
    static constexpr IData/*31:0*/ tb_top__DOT__i_bar__DOT__i_tlp_ur_completer__DOT__REQUEST_FIFO_DEPTH = 0x00000100U;
    static constexpr IData/*31:0*/ tb_top__DOT__i_bar__DOT__i_bar_rsp_arbiter__DOT__FIFO_DEPTH = 0x00000020U;
    static constexpr IData/*31:0*/ tb_top__DOT__i_bar__DOT__i_bar0__DOT__BAR_SIZE = 0x00004000U;
    static constexpr IData/*31:0*/ tb_top__DOT__i_bar__DOT__i_bar0__DOT__BAR_STORAGE_BYTES = 0x00001000U;
    static constexpr IData/*31:0*/ tb_top__DOT__i_bar__DOT__i_bar0__DOT__BAR_WORDS = 0x00000400U;
    static constexpr IData/*31:0*/ tb_top__DOT__i_bar__DOT__i_bar0__DOT__BAR_WORD_ADDR_BITS = 0x0000000aU;
    static constexpr IData/*31:0*/ tb_top__DOT__i_bar__DOT__i_latency_emu__DOT__MIN_LATENCY_CYCLES = 3U;
    static constexpr IData/*31:0*/ tb_top__DOT__i_bar__DOT__i_latency_emu__DOT__MAX_LATENCY_CYCLES = 0x0000000fU;
    static constexpr IData/*31:0*/ tb_top__DOT__i_bar__DOT__i_latency_emu__DOT__AVG_LATENCY_CYCLES = 7U;
    static constexpr IData/*31:0*/ tb_top__DOT__i_bar__DOT__i_latency_emu__DOT__ENABLE_JITTER = 1U;
    static constexpr IData/*31:0*/ tb_top__DOT__i_bar__DOT__i_latency_emu__DOT__BURST_CORRELATION = 0x00000080U;
    static constexpr IData/*31:0*/ tb_top__DOT__i_bar__DOT__i_latency_emu__DOT__THERMAL_DRIFT_PERIOD = 0x00008000U;
    static constexpr IData/*31:0*/ tb_top__DOT__i_bar__DOT__i_latency_emu__DOT__WR_MIN_LATENCY = 2U;
    static constexpr IData/*31:0*/ tb_top__DOT__i_bar__DOT__i_latency_emu__DOT__WR_MAX_LATENCY = 8U;
    static constexpr IData/*31:0*/ tb_top__DOT__i_bar__DOT__i_latency_emu__DOT__CPL_TIMEOUT_CYCLES = 0x00010000U;
    static constexpr IData/*31:0*/ tb_top__DOT__i_bar__DOT__i_latency_emu__DOT__PRNG_SEED_0 = 0xc049b907U;
    static constexpr IData/*31:0*/ tb_top__DOT__i_bar__DOT__i_latency_emu__DOT__PRNG_SEED_1 = 0xc85a4b71U;
    static constexpr IData/*31:0*/ tb_top__DOT__i_bar__DOT__i_latency_emu__DOT__PRNG_SEED_2 = 0x644c6af7U;
    static constexpr IData/*31:0*/ tb_top__DOT__i_bar__DOT__i_latency_emu__DOT__PRNG_SEED_3 = 0x6541532eU;
    static constexpr QData/*63:0*/ tb_top__DOT__i_bar__DOT__NVME_ADVERTISED_LBAS = 0x00000000773bd2b0ULL;

    // CONSTRUCTORS
    Vtop___024root(Vtop__Syms* symsp, const char* namep);
    ~Vtop___024root();
    VL_UNCOPYABLE(Vtop___024root);

    // INTERNAL METHODS
    void __Vconfigure(bool first);
};


#endif  // guard
